### ISSUE TITLE
untilDestroyed with angular9 but without Ivy not working

### ISSUE THREAD

**Issue by CP-Ram** [ngneat/until-destroy#105]
I have advance angular based application.
I am using angular9 `^9.1.11` without Ivy `"enableIvy": false`. And `"ngx-take-until-destroy": "^5.4.0"`
here is the example

**myService:**
`public addNewEntity$ = new Subject();`

**myComponent:**
```
import { untilDestroyed } from 'ngx-take-until-destroy';
@Component({
  selector: 'myapp',
  templateUrl: './myapp.component.html',
  styleUrls: ['./myapp.component.styles.scss']
})
export class MyAppComponent implements AfterViewInit {
constructor(private myService:MyService){
this.myService.addNewEntity$.pipe(untilDestroyed(this)).subscribe((res: any) => {});
}
ngOnInit() {}

ngAfterViewInit() {}

ngOnDestroy() {}
}
```
And it's keep on subscribing and not destroying on component destroy.but it was working fine with angular8.

**Comment by arturovt** [comment]
Provide a reproducible example?

**Comment by Vbyec** [comment]
@CP-Ram I have the same problem with Angular 9.0.5 
Upgrade to the latest 9 version solve it

**Comment by NetanelBasal** [comment]
Can we close this one based on @Vbyec answer?

**Comment by CP-Ram** [comment]
@NetanelBasal  as i already told i m using angular9 `^9.1.11`  .Anyway currently i m little bit busy with other work.i will try this one later.
