### ISSUE TITLE
Getting a compilation error when compiling components with Tsnode

### ISSUE THREAD

**Issue by jedmundo** [ngneat/until-destroy#106]
Hello everybody,

I have a tricky problem. 

I have the **Angular CLI v9 + Angular v9** running concurrently with a **node express server** transpiled with **tsnode** that serves our REST backend mocks as JSON.

The problem is that this **node mock server** transpiles typescript files that import some interfaces and components that exist in our angular app, and although it doesn't use the Angular components themselves (only the interfaces), it still transpiles them.

So when it tries to transpile components with the **@UntilDestroy** decorator, it gives and error (because Ivy isnt compiled yet - and in this case doesn't need to be):

```
/node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:79
  Object.defineProperty(type, defName, {
                                       ^
TypeError: Cannot read property 'get' of undefined
    at decorateDirectiveJIT (/Users/3868648/Projects/sail-frontend/node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:79:40)
    at decorateDirective (/Users/3868648/Projects/sail-frontend/node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:104:4)
    at /Users/3868648/Projects/sail-frontend/node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:117:6
    at DecorateConstructor (/Users/3868648/Projects/sail-frontend/node_modules/reflect-metadata/Reflect.js:541:33)
    at Object.decorate (/Users/3868648/Projects/sail-frontend/node_modules/reflect-metadata/Reflect.js:130:24)
    at Object.__decorate (/Users/3868648/Projects/sail-frontend/node_modules/tslib/tslib.js:96:96)
```

I was able to easily fix this by adding a check for the variable being used on line 76 of [this file](https://github.com/ngneat/until-destroy/blob/master/src/lib/until-destroy.ts):

```javascript
...
const property = Object.getOwnPropertyDescriptor(type, defName);
if (!property) {
  return;
}
  var getter = property.get;
...
```

How to reproduce:

- Go to the [Repo that reproduces the bug](https://github.com/jedmundo/ng-until-destroy-bug) and clone it
- Run `npm install`
- Run `npm run mockserver` you will see the error.

Do you think it makes sense? I can create a PR for this.

If you have any comments/suggestions please let me know.

**Comment by FrancescoBorzi** [comment]
confirmed, I got the same issue

**Comment by Yehonal** [comment]
ts-node does not transpile node_modules by default and I don't think you can force it to do it

I had same issue on other projects

**Comment by arturovt** [comment]
Provide a _minimal reproducible example_, please.

**Comment by jedmundo** [comment]
Here it is @arturovt , sorry for the delay - https://github.com/jedmundo/ng-until-destroy-bug

**Comment by vladimirdrayling** [comment]
Same here while testing nrwl/nx@^9.5.1 based apps using jest with until-destroy@^7.3.2:

```ts
    TypeError: Cannot read property 'get' of undefined

      13 |   templateUrl: './some.component.html',
      14 | })
    > 15 | export class SomeComponent {
         |                           ^

      at decorateDeclarableJIT (../../../../node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:76:65)
      at decorateDeclarable (../../../../node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:102:5)
      at ../../../../node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:115:7
      at Object.__decorate (../../../../node_modules/tslib/tslib.js:97:99)
      at Object.<anonymous> (src/lib/some.component.ts:15:45)
      at Object.<anonymous> (src/lib/some.component.spec.ts:10:1)
```

**Comment by arturovt** [comment]
Guys, please refer to the _README_.

@jedmundo I cloned your reproduction (thx for this) and the error is obvious. Ivy is disabled in your app:

![image](https://user-images.githubusercontent.com/7337691/87652318-bb35b800-c75c-11ea-9388-cf3306065e5b.png)

And if I run `ngcc` to execute the Ivy view compiler then it gets enabled:

![image](https://user-images.githubusercontent.com/7337691/87652407-d9031d00-c75c-11ea-9ae5-b5ebe20e559e.png)

`yarn mockserver` doesn't error anymore:

![image](https://user-images.githubusercontent.com/7337691/87652444-e5877580-c75c-11ea-992f-df37cad017e3.png)

**Comment by vladimirdrayling** [comment]
@arturovt thanks for the hint!

I have an `nrwl/nx@^9.1.5` workspace based on `angular@^9.1.12` package.

After running the `nx s` command, the code
```ts
import('@angular/core').then(core => console.log(core.ɵivyEnabled));
```
prints `true`.

If I run tests the `ɵivyEnabled` is false.

How can I run tests with ivy enabled? Or how to test a component with `until-destory`?

> Btw I didn't find any example tests in the `integration/app` folder of `ngneat/until-destroy` package.

**Comment by FFKL** [comment]
@vladimirdrayling maybe [issue 90](https://github.com/ngneat/until-destroy/issues/90) helps you.

**Comment by arturovt** [comment]
@vladimirdrayling hey. The problem is that Nx workspace has a wrong `postinstall` script, it targets files with `--first-only` argument which means the Ivy compiler transforms only ES2015 files. Jest is a NodeJS module which means it will try to get the `main` property in the `package.json`, Angular provides UMD bundles there. Run plain `ngcc` command without arguments and you will see the magic :wink:

**Comment by arturovt** [comment]
> Btw I didn't find any example tests in the integration/app folder of ngneat/until-destroy package.

There is an `app.component.spec.ts`.
