### ISSUE TITLE
Migration script not working when using angular/cli projects folder

### ISSUE THREAD

**Issue by Aaltuj** [ngneat/until-destroy#107]
Issue:

Running the `npx @ngneat/until-destroy --removeOnDestroy` command doesn't migrate the content when the project has a projects folder.

Solution:

looking at the script the `var base = 'app'` seems to be the issue. Please extend it or allow a user override.

I've run the script by changing the  `base` variable to 'projects'

**Comment by arturovt** [comment]
Good point. Would you want to make a PR?

**Comment by Aaltuj** [comment]
I'll try to make time. keep you posted.

**Comment by arturovt** [comment]
I guess you could add some additional argument like `--base` (or name it how you'd like) under which the user could provide a list of folders:
```shell
npx @ngneat/until-destroy --removeOnDestroy --base=app,projects
```

P.S. just thinking aloud :)

**Comment by wlucha** [comment]
I also experienced that currently the migration script needs to be started in the "src" folder or?

**Comment by catchshyam** [comment]
Is there a workaround to use the migration script until the proper fix arrives? My Angular 9 upgrade is stuck here. Thanks.

**Comment by NetanelBasal** [comment]
Try the latest version: `npx @ngneat/until-destroy --base=my/path
`
