### ISSUE TITLE
Documentation: Annotation order is important

### ISSUE THREAD

**Issue by jaco-terbraak** [ngneat/until-destroy#109]
It appears that the annotation order is important, a detail which is not made apparent in the documentation. If one puts `@UntilDestroy()` after `@Component`, it will crash during Jasmine testing with `Uncaught TypeError: Cannot read property 'onDestroy' of undefined`.

Please update the documentation with a hint that the annotation order matters.

**Comment by FFKL** [comment]
@NetanelBasal I think, you can close this issue
