### ISSUE TITLE
Migration tool misplaces @UntilDestory() when components are annotated with a comment

### ISSUE THREAD

**Issue by wfairclough** [ngneat/until-destroy#113]
After running the migration tool on our repository the components that had comments do not add the `@UntilDestory()` on its own new line.

Example:
```
@@ -25,10 +24,10 @@ export interface DisplayInlineSupportedComponent {
 
 /**
  * Displays chslInput's value outside of host component.
- */
+ */@UntilDestroy()
 @Component({
-  selector: 'chsl-control-value-display',
-  template: `
+      selector: 'chsl-control-value-display',
+      template: `
     <div
       class="chsl-control-value-display"
       [ngClass]="{
```

**Comment by NetanelBasal** [comment]
@arturovt @FFKL this is something we want to support?

**Comment by NetanelBasal** [comment]
@wfairclough it's hard to understand what we see.

**Comment by wfairclough** [comment]
Here is a screenshot instead. It is really just a small formatting problem. Not hard to manually fix either, but just thought I would mention it here.
![image](https://user-images.githubusercontent.com/1356641/87427870-702a7200-c5af-11ea-8219-c0094157c9aa.png)

**Comment by NetanelBasal** [comment]
Ok, I'll leave the decision to @FFKL

**Comment by FFKL** [comment]
@wfairclough @NetanelBasal I'll fix it :smile:
