### ISSUE TITLE
Temp issue

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/until-destroy#115]
@arturovt check this one: https://github.com/angular/angular/commit/737506e79cbda87d8545a663bdd618a884c2e60e

**Comment by arturovt** [comment]
I guess since it gets released we will not need to override `def.onDestroy` but do like with services by overriding `prototype.ngOnDestroy`.

**Comment by NetanelBasal** [comment]
Yes, it's worth to know it, but for now, I wouldn't make any changes/
