### ISSUE TITLE
ng-connect-state - any interest in pulling it into the @ngeat family?

### ISSUE THREAD

**Issue by Rush** [ngneat/until-destroy#116]
Hey, I just created a package called ng-connect-state and I heavily rely on @ngneat/until-destroy to achieve what I want. Plus the boilerplate for the project was shamefully copied from your repo.

https://github.com/Rush/ng-connect-state

If you like it, would you be interested in pulling it into the `@ngeat` family? Otherwise just feel free to close the ticket :)

If you have any feedback such as "terrible idea", "wonderful idea" - that's a good outcome for me as well!

**Comment by NetanelBasal** [comment]
DM me on Twitter, please.
