### ISSUE TITLE
Unsubscribing does not work

### ISSUE THREAD

**Issue by Moik** [ngneat/until-destroy#118]
After recent updates UntilDestroy just stopped working. 
"@angular/core": "~10.0.5"
"@ngneat/until-destroy": "^7.3.2"
[example](https://stackblitz.com/edit/angular-ivy-kqzeep?embed=1&file=src/app/route2/route2.component.ts)

**Comment by Art2058** [comment]
Same issue!

**Comment by Art2058** [comment]
It worked fine 3 days ago.

**Comment by Dok11** [comment]
Same issue. Updated to angular 10 and unsubscribtion stop worked. My package.json:
```
  "dependencies": {
    "@angular/animations": "~10.0.5",
    "@angular/cdk": "^10.1.0",
    "@angular/common": "~10.0.5",
    "@angular/compiler": "~10.0.5",
    "@angular/core": "~10.0.5",
    "@angular/forms": "~10.0.5",
    "@angular/platform-browser": "~10.0.5",
    "@angular/platform-browser-dynamic": "~10.0.5",
    "@angular/router": "~10.0.5",
    "@ngneat/until-destroy": "^7.3.2",
    "rxjs": "~6.6.0",
    "tslib": "^1.13.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.4",
    "@angular/cli": "~10.0.4",
    "@angular/compiler-cli": "~10.0.5",
    "@angularclass/hmr": "^2.1.3",
    "codelyzer": "^5.1.2",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.7"
  }
```

**Comment by Dok11** [comment]
Even with `@UntilDestroy({ checkProperties: true })` auto unsubscription not working

**Comment by arturovt** [comment]
`@ngneat/until-destroy@8.0.0` has been published. Could you give it a try? P.S. it requires Angular 10+.

**Comment by bbarry** [comment]
Can confirm it does work.

the angular min version should probably be 10.0.5 though because that was the version that fixed the lifecycle hook changes: https://github.com/angular/angular/blob/master/CHANGELOG.md#1005-2020-07-22

> * **core:** Allow modification of lifecycle hooks any time before bootstrap (#38119) (14b4718), closes #30497

**Comment by arturovt** [comment]
> version should probably be 10.0.5

Yes, makes sense. I will have time to publish `8.0.1` tomorrow with another requirement. Ping here if you observe any issues.

**Comment by arturovt** [comment]
`@ngneat/until-destroy@8.0.1` has been published and requires `"@angular/core": ">=10.0.5"`

**Comment by arturovt** [comment]
@Moik can the issue be closed?

**Comment by Moik** [comment]
@arturovt I closed the issue, thanks for the quick fix )
