### ISSUE TITLE
Drop UntilDestroy decorator

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/until-destroy#122]
In the latest Angular version, we can achieve the same functionality by using only the `untilDestroy` operator. We'll drop support for Pipes for now.

**Comment by NetanelBasal** [comment]
@arturovt, thinking out loud.

I'm pretty sure that with the new version the following code should work without the decorator:

```ts
const name = '__takeUntilDestroy';

export const takeUntilDestroyed = (
  componentInstance,
  destroyMethodName = 'ngOnDestroy'
) => <T>(source: Observable<T>) => {
  const originalDestroy = componentInstance[destroyMethodName];

  if (!componentInstance[name]) {
    componentInstance[name] = new Subject();

    componentInstance[destroyMethodName] = function() {
      isFunction(originalDestroy) && originalDestroy.apply(this, arguments);
      componentInstance[name].next(true);
      componentInstance[name].complete();
    };
  }
  return source.pipe(takeUntil<T>(componentInstance[name]));
};
```

I think that we could leave the current functionality (or simplify it) because the decorator exposes more options such as `{ checkProperties: true }` and support pipes.

We can create the `takeUntilDestroyed` operator that'll be used with the current Angular version and above.

The disadvantages are:
- We can't separate the peer dependency. 
- It's probably will be confusing.

Another option will be to create it as a separate package `@ngneat/take-until-destroy`, which will be in this repo. 

What do you think?

**Comment by arturovt** [comment]
@NetanelBasal 
Hey. I consider it to be a good idea. I think I might have time to have a look at this in 4-5 days.

**Comment by bbarry** [comment]
here is a cleaned up version according to my project's linter and as a mostly source compatible change (breaking in the case of pipes I guess and other decorator options but I suppose suitable for a major version number increase):

```typescript
// --------
// was until-destroy.ts
/** @deprecated safe to remove (no-op); no longer supports Pipes; no longer supports options  */
export function UntilDestroy(): ClassDecorator {
  return () => {};
}

// --------
// was internals.ts
function isFunction(target: unknown) {
  return typeof target === 'function';
}

const symbolMap: Record<string, symbol> = {};
/**
 * If we use the `untilDestroyed` operator multiple times inside the single
 * instance providing different `destroyMethodName`, then all streams will
 * subscribe to the single subject. If any method is invoked, the subject will
 * emit and all streams will be unsubscribed. We wan't to prevent this behavior,
 * thus we store subjects under different symbols.
 */
function getSymbol(destroyMethodName: string): symbol {
  // fixed bug here (if you pass ngOnDestroy explicitly you get a new symbol)
  if (symbolMap[destroyMethodName]) return symbolMap[destroyMethodName];
  symbolMap[destroyMethodName] = Symbol(`__destroy__${destroyMethodName}`);
  return symbolMap[destroyMethodName];
}

// --------
// was until-destroyed.ts
import { Observable, Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

export const untilDestroyed = (componentInstance: any, destroyMethodName: string = 'ngOnDestroy') => <T>(
  source: Observable<T>
  // linter doesn't like missing explicit return type
): Observable<T> => {
  const originalDestroy = componentInstance[destroyMethodName];
  const name = getSymbol(destroyMethodName);

  if (!componentInstance[name]) {
    componentInstance[name] = new Subject();

    componentInstance[destroyMethodName] = function () {
      if (isFunction(originalDestroy)) {
        // linter doesn't like 'unused expression'
        originalDestroy.apply(this, arguments);
      }
      componentInstance[name].next(true);
      componentInstance[name].complete();
    };
  }
  return source.pipe(takeUntil<T>(componentInstance[name]));
};
```


That said you could convert the existing decorator to support the previous class subscription member features, simply not being required anymore for operator usages.

**Comment by VamsiDharmaji** [comment]
@NetanelBasal @bbarry  I tried with angular 10.0.9 and still not able to override the lifecycle hook on component instances using `componentInstance[destroyMethodName] = function ()` 

Which next angular version are guys referring to where `untilDestroy ` operator would be work without the decorator?

**Comment by arturovt** [comment]
@bbarry you're welcome to make a PR ;)

**Comment by bbarry** [comment]
After I've tested it (haven't done so yet I just copied the files into my project and cleaned up the implementation at the top here).

@VamsiDharmaji it should be possible in everything post 10.0.5 due to the change made for https://github.com/angular/angular/issues/30497

**Comment by codeprizm** [comment]
> After I've tested it (haven't done so yet I just copied the files into my project and cleaned up the implementation at the top here).
> 
> @VamsiDharmaji it should be possible in everything post 10.0.5 due to the change made for [angular/angular#30497](https://github.com/angular/angular/issues/30497)

Thank you @bbarry

**Comment by VamsiDharmaji** [comment]
> After I've tested it (haven't done so yet I just copied the files into my project and cleaned up the implementation at the top here).
> 
> @VamsiDharmaji it should be possible in everything post 10.0.5 due to the change made for [angular/angular#30497](https://github.com/angular/angular/issues/30497)

@bbarry thank you

**Comment by bbarry** [comment]
@VamsiDharmaji, @NetanelBasal  I can confirm the above code does not seem to work. It runs the `componentInstance[destroyMethodName] = function ()` assignment but the method is never called. According to the PR https://github.com/angular/angular/pull/35464 you can modify the lifecycle hooks any time before initialization but nothing after the initialization is certain to run.

The decorator can probably be cleaned up a little and maybe some changes can be done to make it easier to share the attribute from a base class but I think this issue should probably be wontfixed sadly.

**Comment by danzrou** [comment]
@NetanelBasal AFAIK (and tested) you can drop the decorator.
You can leverage use of `Object.getPrototypeOf`:

```ts
const name = symbol('__takeUntilDestroy');

export const takeUntilDestroyed = (
  componentInstance,
  destroyMethodName = 'ngOnDestroy'
) => <T>(source: Observable<T>) => {
  const proto = Object.getPrototypeOf(componentInstance);
  const originalDestroy = proto[destroyMethodName];

  if (!componentInstance[name]) {
    componentInstance[name] = new Subject();

    proto[destroyMethodName] = function() {
      isFunction(originalDestroy) && originalDestroy.apply(this, arguments);
      componentInstance[name].next(true);
      componentInstance[name].complete();
    };
  }
  return source.pipe(takeUntil<T>(componentInstance[name]));
};
```

**Comment by NetanelBasal** [comment]
Yes, the commit comment is misleading. It's too late as Angular already reference it in `TView.destroyHooks`.

Here's a quick pseudo code that works (didn't check all the cases ), but I don't know if we need to use it:

```ts
function untilDestroyed(instance) {
  const [, original] = instance.__ngContext__[1].destroyHooks;

  if (!instance[DESTROY]) {
    instance[DESTROY] = new Subject();
  }

  const TView = instance.__ngContext__[1];

  TView.destroyHooks[1] = function() {
    original?.();
    instance[DESTROY].next();
    instance[DESTROY].complete();
  };

  return takeUntil(instance[DESTROY]);
}
```

**Comment by NetanelBasal** [comment]
I'm closing the issue for now.
