### ISSUE TITLE
Add standard version support

### ISSUE THREAD

**Issue by dmytro-gokun** [ngneat/until-destroy#127]

**Comment by dmytro-gokun** [comment]
Does anyone care? :)

**Comment by arturovt** [comment]
We do care, we just have a really limited amount of time hehe :stuck_out_tongue_closed_eyes: 
We don't mind helping you us. So if you've got a desire to contribute we're welcome, it's appreciated!

**Comment by dmytro-gokun** [comment]
That is the first time I hear 3rd party which does not take part in development to be asked to help with changelog :)

**Comment by NetanelBasal** [comment]
@dmytro-gokun don't forget this is open-source. We'll do things when we have the time. If you don't like our progress, feel free not to use it :)

**Comment by NetanelBasal** [comment]
@arturovt btw, based on the commits, I think 8.0.2 is a redundant release because the only thing I see is that you updated the README file. Am I missing something?

**Comment by dmytro-gokun** [comment]
@NetanelBasal Rest assured, i remember that. Moreover, i run an opensource project myself and answer to ppl who are too demanding exactly the way you just answered me. Nevertheless, maintaining changelog is not something which has to be 'outsourced' (IMO). Moreover, there are tools which do that automatically (e.g. conventional-changelog).

In any case, thanks a lot for the great project and sorry if I sounded rude.

**Comment by NetanelBasal** [comment]
It's ok. In all my other open sources we use [standard version](https://github.com/conventional-changelog/standard-version). We'll add it here when we found the time.

**Comment by arturovt** [comment]
> That is the first time I hear 3rd party which does not take part in development to be asked to help with changelog :)

Lol

**Comment by arturovt** [comment]
> @arturovt btw, based on the commits, I think 8.0.2 is a redundant release because the only thing I see is that you updated the README file. Am I missing something?

Yeah. The problem is that package _standard-changelog_ doesn’t work well. I tried to run it and it doesn’t generate change log for 8.0.2 version. Prolly need to try another package that you proposed.

**Comment by NetanelBasal** [comment]
Sure, no problem.

**Comment by dmytro-gokun** [comment]
Thanks, guys 🥇
