### ISSUE TITLE
Possible Memory Leak Issue

### ISSUE THREAD

**Issue by BBX999** [ngneat/until-destroy#132]
I've been using until-destroy all over my app and I recently solved a memory leak issue where components were not getting released from memory after being destroyed.

I ended up solving the problem by replacing untilDestroyed(this) with a takeUntil(destroy$) pattern in an already non-singleton service (so it gets destroyed with the component). Since simply replacing that line solved the leak, it leads me to believe the problem was with until-destroy not behaving as expected.

I just thought I would bring it to your attention, as it seemed like the right thing to do. But I don't have time to create a reproducible example, and at this point I'm going to be switching over to the takeUntil(destroy$) pattern which seems very straightforward and less concern for things happening under the hood.

In case it helps you, this was the observable subscription causing the leak:

    obs$.pipe(
      filter(ready => !!ready),
      switchMap(() => obs2$),
      filter(formGroup => !!formGroup),
      switchMap((formGroup: FormGroup) => obs3$,
      filter(form => !!form),
      tap((currentForm: TForm) => doSomething(currentForm)),
      untilDestroyed(this),
    ).subscribe();

and replacing untilDetroyed with takeUntil like this fixed the leak:

  destroy$: Subject<void> = new Subject<void>();

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

    obs$.pipe(
      filter(ready => !!ready),
      switchMap(() => obs2$),
      filter(formGroup => !!formGroup),
      switchMap((formGroup: FormGroup) => obs3$,
      filter(form => !!form),
      tap((currentForm: TForm) => doSomething(currentForm)),
      takeUntil(this.destroy$),
    ).subscribe();

**Comment by arturovt** [comment]
Could you provide a minimal reproducible example?

**Comment by BBX999** [comment]
I wasn't really looking for help, just thought I'd let you know there might be an issue to be on the look out for.
I tried to reproduce it just now, as it also doesn't feel right to just say "you may have a major bug" and then just walk away.
I could not reproduce it in stackblitz, however, see the screencast I just took showing the simply component and the console log on the right where after the component is destroyed, the subscription lives on.

It seems the problem may have something to do with factors outside of the component itself, but I don't know what I'd try next to figure that out. What I do know is that if I use the takeUntil instead of untilDestroyed(this) in this context, there is no leak.

I hope it is helpful for you.

https://srv-file16.gofile.io/downloadStore/srv-store3/2ZbchU/memory%20leak.mov

**Comment by arturovt** [comment]
I haven't used the _gofile_ but I'm not gonna open it:

![image](https://user-images.githubusercontent.com/7337691/96256902-22fcd880-0fc2-11eb-8645-93c10cd18877.png)

Could you convert the `.mov` file to `.gif` and paste here directly?

**Comment by BBX999** [comment]
Sure. Here is the mov as a GIF.
![memory leak](https://user-images.githubusercontent.com/20671896/96257325-d5cd3680-0fc2-11eb-8f0a-3665b7809b81.gif)

**Comment by arturovt** [comment]
Interesting, I see your issue. I'll check that one but I'm afraid I'm unable to do anything if I can't reproduce it :disappointed:

**Comment by arturovt** [comment]
If you put such `console.log`'s:
```ts
ngAfterViewInit(): void {
    interval(2000)
      .pipe(
        switchMap(() => interval(500).pipe(tap((value) => console.log(value)))),
        untilDestroyed(this),
        finalize(() => {
          console.log('finalize...');
        })
      )
      .subscribe({
        complete: () => {
          console.log('complete...');
        },
      });
  }
```

None of them are run?

**Comment by arturovt** [comment]
Could you paste the results of such commands here:
```bash
yarn ng version
```

and:

```bash
node -e 'console.log(require("@ngneat/until-destroy/package.json").version)'
```

**Comment by BBX999** [comment]
> If you put such `console.log`'s:
> 
> ```ts
> ngAfterViewInit(): void {
>     interval(2000)
>       .pipe(
>         switchMap(() => interval(500).pipe(tap((value) => console.log(value)))),
>         untilDestroyed(this),
>         finalize(() => {
>           console.log('finalize...');
>         })
>       )
>       .subscribe({
>         complete: () => {
>           console.log('complete...');
>         },
>       });
>   }
> ```
> 
> None of them are run?

Correct, when I add those console.log's, they do not show up in the console.

**Comment by BBX999** [comment]
> Could you paste the results of such commands here:
> 
> ```shell
> yarn ng version
> ```
> 
> and:
> 
> ```shell
> node -e 'console.log(require("@ngneat/until-destroy/package.json").version)'
> ```

yarn run v1.22.4
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.6
Node: 12.13.1
OS: darwin x64

Angular: 10.1.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.6
@angular-devkit/build-angular      0.1001.6
@angular-devkit/core               10.1.6
@angular-devkit/schematics         10.1.6
@angular/cdk                       10.2.4
@angular/cli                       10.1.6
@angular/material                  10.2.4
@angular/material-moment-adapter   9.2.4
@schematics/angular                10.1.6
@schematics/update                 0.1001.6
rxjs                               6.5.5
typescript                         4.0.3
    
✨  Done in 0.57s.

node -e 'console.log(require("@ngneat/until-destroy/package.json").version)'
7.3.2

**Comment by arturovt** [comment]
Oh man, could you try to upgrade to the latest `@ngneat/until-destroy` version? It's `8.0.2`.

**Comment by BBX999** [comment]
That fixed the leak. Nice job, I guess that was an important upgrade :)

**Comment by arturovt** [comment]
Good to hear. Could you close the issue if it's resolved? I'll probably need to update the README to mention that Angular 10 should be used only with 8+ version.

**Comment by BBX999** [comment]
Will do. Thank you.
