### ISSUE TITLE
Slight gotcha when upgrading

### ISSUE THREAD

**Issue by AshMcConnell** [ngneat/until-destroy#137]
Hi Folks,

I upgraded from `"ngx-take-until-destroy": "^5.4.0"` and ran the upgrade script.  It worked great, but there is a slight issue that I came across.

If you have a providers that reference the class being defined you **must** use forwardRef.  

e.g. this must change

``` typescript    
providers: [
        {provide: NG_VALUE_ACCESSOR, useExisting: SomeComponent, multi: true}
    ]
})
export class SomeComponent
```

to this: -

``` typescript    
providers: [
        {provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => SomeComponent), multi: true},
    ]
})
export class SomeComponent
```

It might help someone to mention it in the docs?  Or perhaps I just didn't know enough about how forwardRef works.

**Comment by arturovt** [comment]
Maybe I'm missing something but how is it related to this package? :)

**Comment by AshMcConnell** [comment]
Ha, sorry, I might have the wrong end of the stick, but I'm pretty sure when my component is decorated with `@UntilDestroy()` it must use forwardRef whereas it was working without the forwardRef before.

I'll hunt out the error I was getting when I get back to work on Monday if it's useful

**Comment by NetanelBasal** [comment]
I'm closing the issue. If you have any additional information, feel free to re-open it.
