### ISSUE TITLE
Compatibility with Angular 11

### ISSUE THREAD

**Issue by eyupaltindal** [ngneat/until-destroy#138]
Hi,
I want to use this package with angular11. I think, there is a problem with angular 11. It seems they don't work together.

`
  "dependencies": {
    "@angular/animations": "~11.0.2",
    "@angular/cdk": "^11.0.1",
    "@angular/common": "~11.0.2",
    "@angular/compiler": "~11.0.2",
    "@angular/core": "~11.0.2",
    "@angular/fire": "^6.1.2",
    "@angular/forms": "~11.0.2",
    "@angular/google-maps": "^11.0.1",
    "@angular/localize": "^11.0.2",
    "@angular/platform-browser": "~11.0.2",
    "@angular/platform-browser-dynamic": "~11.0.2",
    "@angular/router": "~11.0.2",
    "@ngneat/until-destroy": "^8.0.3"
}
`

**Comment by arturovt** [comment]
Why?

**Comment by eyupaltindal** [comment]
> Why?

**Comment by eyupaltindal** [comment]
The subscription still works when my component destroy. 
With angular 10.0.2 and until-destroy 7.1.2 it was working great.

**Comment by arturovt** [comment]
https://github.com/ngneat/until-destroy#angular-10-compatibility

**Comment by arturovt** [comment]
This repository uses the latest Angular version which is 11, we also have a lot of integration tests that ensure that unsubscription happens. I cannot say anything until the minimal reproducible example is provided.
