### ISSUE TITLE
TypeError: Cannot read property 'onDestroy' of undefined -- paths to resolution

### ISSUE THREAD

**Issue by cryptobrains** [ngneat/until-destroy#145]
I don't want to just submit a patch here for the problem as it would assume developer intent. Let's see what the problem is.

I've traced the bug in one scenario. If you decorate a regular class (not a component) with @UntilDestroyed() (which used to execute silently even if it perhaps should not have ?), instantiate it directly (myVar = new MyClass())  then this call in decorateDeclarable(type, options)

    def.onDestroy = decorateNgOnDestroy(def.onDestroy, options);
    
triggers the error.

If you just want to avoid the error (and keep the buggy assumptions of decorated classes) then the error can be suppressed by bracketing the code:

`
  if (def !== undefined) {
        def.onDestroy = decorateNgOnDestroy(def.onDestroy, options);
        markAsDecorated(def);
  }
`

and perhaps adding a warning. However the more constructive behaviour might be to synthesize a way to convert that decorated class into something that behaves like a component with its expected onDestroy lifecycle stage.

**Comment by cryptobrains** [comment]
It's not a question; it addresses the bug people have raised.

**Comment by cryptobrains** [comment]
But you can duplicate it by creating a class

```
@UntilDestroyed()
export class DummyClass {
}
```

and in any component instantiate it in the constructor

```
dummyClass: DummyClass;

constructor () {
  this.dummyClass = new DummyClass();
}
```

**Comment by cryptobrains** [comment]
Was 7.3.2; weird npm update didn't raise it to the latest. Will check under 8 and see if the issue is still there.

**Comment by arturovt** [comment]
Glad you've resolved the issue!

**Comment by cryptobrains** [comment]
I love your libraries by the way. Very well thought-out.
