### ISSUE TITLE
ESLint Rule fails on onDestroy

### ISSUE THREAD

**Issue by brunano21** [ngneat/until-destroy#161]
Hi there,

we have configured the eslint rules as described in the README

*eslintrc.json*
```json
...
{
    "rxjs/no-unsafe-takeuntil": [
        "error",
        {
            "alias": ["untilDestroyed"]
        }
    ],
    "rxjs-angular/prefer-takeuntil": [
       "error",
       {
         "alias": ["untilDestroyed"],
         "checkComplete": true,
         "checkDecorators": ["Component"],
         "checkDestroy": true
       }
    ]
}
...
```

and followed the example like below:

*app.component.ts*
```typescript
import ...

@UntilDestroy()
@Component({})
export class AppComponent implements AfterViewInit {
  ...
  ngAfterViewInit() {
    this.widget.valueChanges.
      .pipe(untilDestroyed(this))
      .subscribe(() => /* do stuff */);
  }
}

// NOTE: No ngOnDestroy is explicitly defined in the component.
```

However, when running the linter, it complains about:
>  `ngOnDestroy` is not implemented                                                rxjs-angular/prefer-takeuntil
>  Forbids calling `subscribe` without an accompanying `takeUntil`  rxjs-angular/prefer-takeuntil

Ideally, we shouldn't need to implement `ngOnDestroy` because `untilDestroy` decorator and `untilDestroyed` operator should take care of that automatically.

Installed packages (based on Angular 11.2):
```
eslint@7.10.0
eslint-plugin-rxjs@3.3.5
eslint-plugin-rxjs-angular@1.0.6
rxjs@6.5.5
ngneat/until-destroy@8.1.1
```

I'm wondering if I'm missing anything somewhere or if this is the expected behaviour - or maybe the ESLint rules are not compatible with untilDestroy/Ivy.

**Comment by brunano21** [comment]
@arturovt  @NetanelBasal - any help with the above?

**Comment by NetanelBasal** [comment]
`"checkDestroy": false`
