### ISSUE TITLE
Support for rxjs@7.1.0

### ISSUE THREAD

**Issue by ABartoszko** [ngneat/until-destroy#162]
Hi,
in my team we need to use until-destroy in a project which has the rxjs version updated to 7.1.0. When installing package there is an error:
```
Found: rxjs@7.1.0
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"7.1.0" from the root project
npm ERR!   peer rxjs@">=6.4.0" from @ngneat/until-destroy@8.1.1
npm ERR!   node_modules/@ngneat/until-destroy
npm ERR!     @ngneat/until-destroy@"*" from the root project
```

Are you planning a support for rxjs@7.1.0?

**Comment by arturovt** [comment]
`@ngneat/until-destroy@8.1.2` has been published with a stricter peer dependencies list.
