### ISSUE TITLE
When used together checkProperties and arrayName => only arrayName seems to work

### ISSUE THREAD

**Issue by peter-stoyanov** [ngneat/until-destroy#181]
When used together checkProperties and arrayName => only arrayName seems to work.

Versions:
- angular 13
- "@ngneat/until-destroy": "9.0.0",

Component that keeps its property assigned subscriptions alive:
```ts
import { Component } from '@angular/core';
import { UntilDestroy } from '@ngneat/until-destroy';
import { Subscription, fromEvent } from 'rxjs';

// When I use both checkProperties and arrayName only arrayName seems to work
@UntilDestroy({
  checkProperties: true,
  arrayName: 'arrayPropSubs',
})
@Component({
  selector: 'child',
  template: `
    <p>Child component works </p>
    <a routerLink="/hello">
      link to hello component
    </a>
  `,
  styles: [
    `
    :host { display: block; background-color: yellow; padding: 20px; }
  `,
  ],
})
export class ChildComponent {
  arrayPropSubs: Subscription[] = [];

  // This is not being unsubscribed
  propSub: Subscription;

  constructor() {
    this.propSub = fromEvent(document, 'click').subscribe(() =>
      console.log('click from prop propSub')
    );

    this.arrayPropSubs.push(
      fromEvent(document, 'click').subscribe(() =>
        console.log('click from array prop subs')
      )
    );
  }
}
```

Steps to reproduce:

- open the example at [link](https://stackblitz.com/edit/angular-ivy-nasr4g?file=src%2Fapp%2Fchild.component.ts)
- click on the link to child component, which will create two subscriptions for document.click event.
- click on the link to hello component
- expected behaviour is that both subscriptions are not active anymore since Child component is destroyed 
```
@UntilDestroy({
  checkProperties: true,
  arrayName: 'arrayPropSubs',
})
```
- actual result is that the subscription on the property is not unsubscribed, the ones in the array are unsubscribed

**Comment by arturovt** [comment]
Hey, I've published `9.0.1` with a fix.
