### ISSUE TITLE
Please change Subject to Replay subject in internals.

### ISSUE THREAD

**Issue by tadavid-cae** [ngneat/until-destroy#186]
Hi There!

We had a very gnarly bug hunt today because of this issue. When the initialization of the component is slow it could happen that the destroy life cycle hook invoked earlier then the actual subscription creation with the untilDestroyed pipe in the ngOnInit. This case specially when you are subscribing to a timer function it will result a free running timer function which will never stop since the emit for the destroy will be earlier then the actual subscription creation. 
To solve this please simply change the new Subject to new ReplaySubject. 

https://github.com/ngneat/until-destroy/blob/017054ba59b60712068bd9f13966c9a48200e0eb/libs/until-destroy/src/lib/internals.ts#L48

Thanks in advance!

**Comment by dtap001** [comment]
You can check it here in the logs:
https://stackblitz.com/edit/angular-fxhwp8

You can see from the console logs that the delayed execution log entries always occuring after ngDestroy and you can see from the contetIndentifier they belong to the same:

ParentComponent ngOnInit 
ChildComponent on init 1649875579946 
ChildComponent on destroy 1649875579946 
ChildComponent on init 1649875585953 
ChildComponent delay execution! 1649875579946
ChildComponent on destroy 1649875585953 
ChildComponent on init 1649875591963 
ChildComponent delay execution! 1649875585953 
ChildComponent on destroy 1649875591963 
ChildComponent on init 1649875597971 
ChildComponent delay execution! 1649875591963
ChildComponent on destroy 1649875597971 
ChildComponent on init 1649875603989 
ChildComponent delay execution! 1649875597971
ChildComponent on destroy 1649875603989 
ChildComponent on init 1649875610006 
ChildComponent delay execution! 1649875603989
ChildComponent on destroy 1649875610006

**Comment by dtap001** [comment]
I know this is a wrong side out solution but this is the exact case in our scenario and I am sure this proposed change (Subject to ReplaySubject) will solve it for us and lot of other people who doesnt take time to raise an issue regarding this :)

**Comment by arturovt** [comment]
I'm not sure how this would be solved by a replay subject. The `untilDestroy` acts as a `takeUntil` operator.

I don't think this somehow will solve issues for other people. You're running asynchronous code unsafely by using promises which are not cancellable and I don't know how this will be solved by changing subject to replay subject. If I change the code to this:
```ts
    interval(1000)
      .pipe(
        switchMap(() => of([1]).pipe(delay(5000))),
        untilDestroyed(this)
      )
      .subscribe(async () => {
        // await of([1]).pipe(delay(5000)).toPromise();
        console.log(
          "ChildComponent delay execution! " + this.contextIdentifier
        );
      });
```

I don't see the message being logged.

**Comment by tadavid-cae** [comment]
> You're running asynchronous code unsafely by using promises which are not cancellable and I don't understand how this would be solved by changing subject to replay subject. If I change the code to this

I am not sure what do mean by uncancelable promise. Promises cannnot be cancelled without any 3rd party promise lib.
However by removing that line from the code you removed the actual cause of the problem which is delayed execution. I dont see se the risks changing that Subject to ReplaySubject. Can you elaborate? This would be transparent for anyone who is not related to this issue but it would solve for us.

---
I have removed the part from the code to make it more secure and I can definitely reproduce the issue with it. You can see the delayed execution is called AFTER the destroy. And if you let it run you can see how the delayed execution lines count increases with every iteration since the observable is not completed because of you are using a Subject instead Replay subject:

> ParentComponent ngOnInit preview-a90493f83da5a.js:2:14685
ChildComponent on init 1649915942322 preview-a90493f83da5a.js:2:14685
ChildComponent on destroy 1649915942322 preview-a90493f83da5a.js:2:14685
ChildComponent on init 1649915948322 preview-a90493f83da5a.js:2:14685
ChildComponent delay execution! 1649915942322

--- 
Accumulation of the execution since the observable is not cleared: 

> ChildComponent on init 1649915960324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent on destroy 1649915960324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent on init 1649915966325 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915960324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915960324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915960324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent on destroy 1649915966325 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915960324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915960324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915960324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent on init 1649915972327 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915966325 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915960324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915966325 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915960324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915966325 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915960324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent on destroy 1649915972327 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915966325 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915960324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915966325 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915960324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915966325 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915960324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915954324 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915948322 [preview-a90493f83da5a.js:2:14685](https://c.staticblitz.com/assets/js/preview-a90493f83da5a.js)
ChildComponent delay execution! 1649915942322

**Comment by tadavid-cae** [comment]
@arturovt  please reopen this issue

**Comment by arturovt** [comment]
I do not understand why you keep showing me promise use cases. **Promises are not cancellable**. Any code will be executed when the microtask is scheduled and then resolved. If I change the code to this:
```ts
console.log("ChildComponent on init " + this.contextIdentifier);
of([1])
  .pipe(
    delay(5000),
    first(),
    switchMap(() => interval(1000)),
    untilDestroyed(this)
  )
  .subscribe(() => {
    console.log("ChildComponent delay execution! " + this.contextIdentifier);
  });
```
I don't see the message being logged.

**Comment by dtap001** [comment]
I understand that they are not cancelable, but ReplaySubject would guard this use case too. :(

**Comment by dtap001** [comment]
@arturovt  Alright. Then is there any possibility to highlight this in the readme? I mean something like this: 

You cannot use until-destroy in a promise to unsubscribe your obserables since promises are not cancelable and in a scenario where you component destroyed before the actual execution of the promise it is not gonna work?

**Comment by Rush** [comment]
Why would this library have to mention things that are unrelated from this library? Your initial example would be equally broken if you called `.unsubscribe()` by yourself. The scope of this library is pretty simple and mentioning in the README every way you can shoot yourself in the foot seems pointless.

**Comment by dtap001** [comment]
@Rush  @arturovt 

I have managed to reproduce it without promises.

https://stackblitz.com/edit/angular-is4qop?file=src%2Fapp%2Fchild%2Fchild.component.ts

You can see how some delayed execution can be stuck see: `1650382893618` or `1650382992059`

> ParentComponent ngOnInit preview-18b9a92777aca.js:2:14685
ChildComponent on init 1650382993417 preview-18b9a92777aca.js:2:14685
Angular is running in development mode. Call enableProdMode() to enable production mode. preview-18b9a92777aca.js:2:14685
ChildComponent on destroy 1650382992659 preview-18b9a92777aca.js:2:14685
ParentComponent ngOnDestroy preview-18b9a92777aca.js:2:14685
ChildComponent registered timer 1650382992059 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382893618 preview-18b9a92777aca.js:2:14685
ChildComponent registered timer 1650382993417 preview-18b9a92777aca.js:2:14685
ChildComponent on destroy 1650382993417 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382992059 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382893618 preview-18b9a92777aca.js:2:14685
ChildComponent on init 1650382997839 preview-18b9a92777aca.js:2:14685
ChildComponent registered timer 1650382997839 preview-18b9a92777aca.js:2:14685
ChildComponent on destroy 1650382997839 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382992059 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382893618 preview-18b9a92777aca.js:2:14685
ChildComponent on init 1650383002266 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382992059 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382893618 preview-18b9a92777aca.js:2:14685
ChildComponent registered timer 1650383002266 preview-18b9a92777aca.js:2:14685
ChildComponent on destroy 1650383002266 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382992059 preview-18b9a92777aca.js:2:14685
ChildComponent on init 1650383006676 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382893618 preview-18b9a92777aca.js:2:14685
ChildComponent registered timer 1650383006676 preview-18b9a92777aca.js:2:14685
ChildComponent on destroy 1650383006676 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382992059 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382893618 preview-18b9a92777aca.js:2:14685
ChildComponent on init 1650383011090 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382992059 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382893618 preview-18b9a92777aca.js:2:14685
ChildComponent registered timer 1650383011090 preview-18b9a92777aca.js:2:14685
ChildComponent on destroy 1650383011090 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382992059 preview-18b9a92777aca.js:2:14685
ChildComponent on init 1650383015510 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382893618 preview-18b9a92777aca.js:2:14685
ChildComponent registered timer 1650383015510 preview-18b9a92777aca.js:2:14685
ChildComponent on destroy 1650383015510 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382992059 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382893618 preview-18b9a92777aca.js:2:14685
ChildComponent on init 1650383019923 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382992059 preview-18b9a92777aca.js:2:14685
ChildComponent delay execution! 1650382893618 preview-18b9a92777aca.js:2:14685
ChildComponent registered timer 1650383019923 preview-18b9a92777aca.js:2:14685
ChildComponent on destroy 1650383019923

**Comment by dtap001** [comment]
So sorry to bother you! Thanks four your replies.

**Comment by ippeiukai** [comment]
This is not a bug indeed, but I personally prefer `new ReplaySubject<void>(1)` to `new Subject<void>(1)` even if only just for peace of mind. It would make sure the component remains destroyed so that observables immediately complete even when some really bad code delays creating observable until ngOnDestroy. 

In above case, this would leak:
```TS
  ngAfterViewInit() {
    console.debug('ChildComponent on init ' + this.contextIdentifier);
    setTimeout(() => {
      interval(1000)
        .pipe(
          untilDestroyed(this),
          tap(() => {
            console.debug('ChildComponent interval ' + this.contextIdentifier);
          })
        )
        .subscribe();
    }, 5000); // component gets destroyed after 3000
  }
```

**Comment by tadavid-cae** [comment]
@ippeiukai  Thank you!
