### ISSUE TITLE
Subscriptions are getting destroyed when pending api call finished are component destroy

### ISSUE THREAD

**Issue by RahulBadenkal** [ngneat/until-destroy#187]
parent component.html
```
<child-component *ngIf="showChild"></child-component>
```

child component.ts
```
@UntilDestroy()
@Component({
	selector: 'child-component',
	templateUrl: './child-component.html',
	styleUrls: ['./child-component.scss']
})
export class MyChildComponent implements OnInit, OnDestroy {
  myStoreData
  constructor(store) {
    this.store
	.select(myData)
	.pipe(untilDestroyed(this))
	.subscribe((myStoreData) => (this.myStoreData= myStoreData));
  }

 async makeApiCall() {
   try {
     let x = await fetch(api) // <-- Lets say this took 5 seconds, and the component was destroyed when this was ongoing
     this.store.dispatch(myActionThatChangesMyStoreData({ data: x ))
     if (this.myStoreData.someCondition) {  // <-- after api is finished and this executed (and the component is destroyed), myStoreData still has old stale data and is not changed from the "myActionThatChangesMyStoreData" action.
       this.store.dispatch(myOtherAction({ data: "abc" ))
     }
    }
    catch (error) {
    }
 }
}
```

Scenario:
When the makeApiCall is executing in the child component and the the showChild variable in parent is made false, the child component is destroyed and thus all subscriptions from store are destroyed because of untilDestroy
But the component is still in memory as there is a pending xhr request and when the request is fulfilled, the further actions depend on store data which are actually outdated (since all subscriptions are unsubscribed) and the whole function logic goes wrong.

So what is am asking is, is it possible to make untilDestroy unsubscribe when all pending xhr requests are completed and not on ngOnDestroy() hook? Or is there a better way to handle such situations? 

Thank you!

**Comment by arturovt** [comment]
I’m not sure how this example is related to this library.

To start with, what’s the reason for using await + fetch except of Angular’s HttpClient with untilDestroyed?

Promises are not cancellable. There’s no way to stop the code execution when the promise is resolved.
