### ISSUE TITLE
9.1.0 version kills NgxTranslate

### ISSUE THREAD

**Issue by petrot** [ngneat/until-destroy#190]
I have the following component declaration:

```
@UntilDestroy()
@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'app-about-page',
  templateUrl: './about.page.html',
  styleUrls: ['./about.page.scss'],
})
```

With this config, NgxTranslate fails with the following message:
```
ERROR Error: Uncaught (in promise): Error: NG0302: The pipe 'translate' could not be found in the 'AboutPage' component!.
```

When I remove the @UntilDestroy() decorator, the translation works well.

This error appeared with v9.1.0.

**Comment by arturovt** [comment]
Hey @petrot . Thanks for the issue, I was guessing that the change _should probably_ cause something related to that. I was just checking it locally in my apps and haven't encountered any issue. But your case confirms that the issue exists.

I'll keep investigating. Do you use JIT or AOT compilation (what's the value of the `aot` option in your configuration or it doesn't exist at all)?

**Comment by petrot** [comment]
Hi @arturovt , the bug exists with the default `"aot": false` settings (build/options in serve mode). When I change it to `true`, it works well.

**Comment by arturovt** [comment]
Thanks for confirming.

**Comment by arturovt** [comment]
I've reverted the change.

**Comment by petrot** [comment]
Thanks!
