### ISSUE TITLE
9.1.0 raises "No provider for SubjectUnsubscribedChecker"

### ISSUE THREAD

**Issue by devfservant** [ngneat/until-destroy#193]
When developing locally, I have some `NullInjectorError` errors:

![image](https://user-images.githubusercontent.com/43757707/166492715-456aef3f-0696-4578-822b-48241013aeb1.png)

They were not there before upgrading to 9.1.0. It is still there with 9.1.1.  

Are they as expected?
Could it come from the use of [createEffect](https://ngrx.io/api/effects/createEffect) from `@ngrx/effects`?

I have a quite big codebase so it is a bit hard to precisely isolate where does the issue come from.

Thank you

**Comment by NetanelBasal** [comment]
@arturovt I would revert this change for now and consider replacing it with an eslint rule if we can't cover all the cases.

**Comment by arturovt** [comment]
@NetanelBasal alright, that makes sense.

**Comment by arturovt** [comment]
I've reverted the change. Will work on the ESLint rule.

**Comment by devfservant** [comment]
Hello,
I've seen that [the revert has been reverted back](https://github.com/ngneat/until-destroy/pull/196), is it as expected?
Thank you
