### ISSUE TITLE
Angular 14 ut could not run correctly 

### ISSUE THREAD

**Issue by constCD** [ngneat/until-destroy#205]
This is my dependencies`"@angular/common": "^14.1.1",
   "@angular/compiler": "^14.1.1",
    "@angular/core": "^14.1.1",
"@ngneat/until-destroy": "^9.2.1",
 "rxjs": "~6.6.0",
 "jest": "^28.1.3",
 "typescript": "~4.6.4",` ,when I run ut like this `  it('registerFilterInputEvents -> filter is true -> keydown event', async () => {
    funcA();
    await funcB();
    funcC();
  });` 
async and await is not work, funC() run directly. And if I rollback @ngneat/until-destroy to @8 version, It`s work. What can I do to solve this issue?thanks

**Comment by arturovt** [comment]
Please, provide a minimal reproducible example.
