### ISSUE TITLE
Angular 14 ut could not run correctly with a a minimal reproducible example

### ISSUE THREAD

**Issue by constCD** [ngneat/until-destroy#207]
This is my dependencies"@angular/common": "^14.1.1", "@angular/compiler": "^14.1.1", "@angular/core": "^14.1.1", "@ngneat/until-destroy": "^9.2.1", "rxjs": "~6.6.0", "jest": "^28.1.3", "typescript": "~4.6.4, "primeng": "^14.0.0",
",
 If I install 9.2.1 the UT is failed, and if I install the 8.0.4 UT is successful, if I remove all 'UntilDestroy, untilDestroyed' at 9.2.1 version the ut is successful . The failed reason is the async and await  not work. It seems 9.x.x have some conflict with the jest or angular14. Thanks

**Comment by constCD** [comment]
I have build a complete project:
[testUntilDestroy.zip](https://github.com/ngneat/until-destroy/files/9372240/testUntilDestroy.zip)
After `npm install`, you can test the result, it is failed at @9 version.

**Comment by arturovt** [comment]
Can you create git repository and push your files there? I don’t wanna download zip archives without a proper virus check.

**Comment by constCD** [comment]
> Can you create git repository and push your files there? I don’t wanna download zip archives without a proper virus check.

https://github.com/constCD/testUntilDestroy Thanks

**Comment by arturovt** [comment]
Hey, I'm getting this when running `ng test`:
```
./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: /home/overthesanity/projects/testUntilDestroy/src/polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

./src/test.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: /home/overthesanity/projects/testUntilDestroy/src/test.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
```

**Comment by constCD** [comment]
> 

I have solved this issue, please pull new code. thanks

**Comment by arturovt** [comment]
Can you provide reproduction steps please?

**Comment by arturovt** [comment]
I was able to reproduce it, will provide a fix shortly.

**Comment by arturovt** [comment]
`@ngneat/until-destroy@9.2.2`.
