### ISSUE TITLE
How to use until-destroy-migration? 

### ISSUE THREAD

**Issue by ivanyurchenko1** [ngneat/until-destroy#215]
Hello. I'm trying to apply the migration as mentioned in the readme. 

I added the package with this command:
`npm i --save-dev @ngneat/until-destroy-migration`

And now I'm trying to do 
`npx @ngneat/until-destroy-migration --base my/path`
which doesn't do anything at all. No errors, no changes. I changed path to mine, also tried to run without path, as well as without `--base` prefix. Nothing is happening.

**Comment by ivanyurchenko1** [comment]
Sure. Create any project, let's say https://stackblitz.com/edit/angular-playground 

Download it, do 
`npm i --save-dev @ngneat/until-destroy-migration`
 and try to apply the 
`npx @ngneat/until-destroy-migration --base my/path`

The same happens - nothing is changed. No errors or anything.

![image](https://user-images.githubusercontent.com/59170893/196912187-eac50c93-c630-467d-ba6c-040f90138b83.png)

**Comment by arturovt** [comment]
But what are you expecting to be done? The migration script is used to move the old view engine API to the new format. The view engine required `ngOnDestroy` to be declared on the class which is not required in Ivy.

**Comment by arturovt** [comment]
Closing as not an issue.
