### ISSUE TITLE
ERROR Error: ASSERTION ERROR: token must be defined [Expected=> null != undefined <=Actual]

### ISSUE THREAD

**Issue by dancornilov** [ngneat/until-destroy#232]
Hey,

I would like to extend my heartfelt appreciation for your remarkable contribution to the open-source community. Your package has become an integral part of many of my projects, and its impact on their success cannot be overstated. However, I have recently encountered a minor yet critical bug that poses a significant challenge, particularly in large-scale projects.

This issue manifests when **using your package** within an Angular component that extends the **ControlValueAccessor**. 

```
ERROR Error: ASSERTION ERROR: token must be defined [Expected=> null != undefined <=Actual]
```

![image](https://github.com/ngneat/until-destroy/assets/24212761/0a7d88ee-3d2a-4c43-866d-ccc5ae3e8e3a)

To facilitate a thorough understanding of the problem, I have prepared a default Angular project that can be used to reproduce the issue. You can access it by following this link: 
https://github.com/dancornilov/va-until-destroy-bug

Thank you for your time and consideration.

**Comment by dancornilov** [comment]
Thanks for quick and descriptive answer, your insights have shed light on the situation.

I wonder if there is a possibility to enhance the error message by incorporating additional validation or implementing supplementary logic. This improvement would greatly benefit developers encountering similar scenarios.

Interestingly, I have a project with a similar implementation of `ControlValueAccessor` & `@UntilDestroy` on **Angular 14**, which functions without encountering any errors.
It is worth noting that this error only started to manifest in **Angular 15+**.

**Comment by arturovt** [comment]
Because you're targetting `es2022`.

**Comment by arturovt** [comment]
> I wonder if there is a possibility to enhance the error message by incorporating additional validation or implementing supplementary logic.

We can't because the error belongs to vague use-cases. This may happen in any implementation (e.g. ReactJS) using TypeScript and decorators.

**Comment by dancornilov** [comment]
Thanks again for your work 🙏.
_(I have no other comments)_
