### ISSUE TITLE
Can untilDestroyed from @ngneat/until-destroy be used with View Engine?

### ISSUE THREAD

**Issue by micobarac** [ngneat/until-destroy#38]
It's unclear from the Readme file whether `untilDestroyed` from `@ngneat/until-destroy` can be used with **View Engine**, or one must use the `untilDestroyed` from `ngx-take-until-destroy`.

Is `@ngneat/until-destroy` reserved for **Ivy** only?

If the answer is affirmative, then migrating to `@ngneat` dependency in case of **View Engine** wouldn't be possible for the time being.

**Comment by NetanelBasal** [comment]
Correct. Use ngx-take-until-destroy if you are working with ViewEngine.
