### ISSUE TITLE
Cannot read property 'onDestroy' in service

### ISSUE THREAD

**Issue by menelai** [ngneat/until-destroy#41]
```
@UntilDestroy()
@Injectable({
  providedIn: 'root'
})
export class MyService implements OnDestroy {
  constructor() {
    interval(1000).pipe(untilDestroyed(this)).subscribe();
  }
}
```

**Comment by NetanelBasal** [comment]
Your service is a wide app singleton, so it does not make sense to use it here.

**Comment by NetanelBasal** [comment]
Also, the Ivy version doesn't support a service.

**Comment by Andrew-Kulpa** [comment]
I also started getting this same error when I tried building for `es5`. Replacing all uses of `untilDestroyed` with unsubscribing within `ngOnDestroy` solved the problem, though I do prefer using the until-destroy way. Also, this was within a component.

**Comment by NetanelBasal** [comment]
@Andrew-Kulpa, can you provide a code example, please?
