### ISSUE TITLE
It is not working on angular v9

### ISSUE THREAD

**Issue by SenAlexandru** [ngneat/until-destroy#52]
I've just tested the example posted on the project page

> ngOnInit() {
>     interval(1000)
>       .pipe(untilDestroyed(this))
>       .subscribe(val => console.log(val));
>   }

and it keeps on logging to console despite destroying the component.
I must point that on another v8 project this library works alright.

**Comment by sid69330** [comment]
Related issue : https://github.com/angular/angular/issues/35336

**Comment by LanderBeeuwsaert** [comment]
Hey yeah, I have this in my ngOnInit:

this.userRightService.rightsCollObs.pipe(untilDestroyed(this)).subscribe(

and pre-ng9/ivy it worked, now it doesn't unsubscribe.

**Comment by NetanelBasal** [comment]
I didn't find the time to check it yet. @arturovt any thoughts?

**Comment by NetanelBasal** [comment]
@SenAlexandru I just upgraded to v9 and it works fine. @arturovt and I test it with the latest RC, and it worked. The API didn't change.

**Comment by NetanelBasal** [comment]
In your example, you need to add the decorator. I published a new version, and tested that it works with v9.

**Comment by SenAlexandru** [comment]
@NetanelBasal Thank you very much. Just as a suggestion I advise to update this information on npmjs.org
[https://www.npmjs.com/package/ngx-take-until-destroy]
Thanks again
