### ISSUE TITLE
whenDestroyed

### ISSUE THREAD

**Issue by Odonno** [ngneat/until-destroy#53]
Hi, would it be possible to create a `whenDestroyed(this)` function the same way we have a `untilDestroyed`?

**Comment by NetanelBasal** [comment]
What for?

**Comment by Odonno** [comment]
In order to detect when the component is destroyed. In my case, I used it to know when to destroy components created with a angular/cdk Portal.

**Comment by NetanelBasal** [comment]
Use ngOnDestroy, we don't have any plans to do it. Thanks for the suggestion.

**Comment by Odonno** [comment]
I want to send an `Observable`, not calling it on the method destroy.. I can show you an example if you want.
