### ISSUE TITLE
Doesn't work on Angular 9

### ISSUE THREAD

**Issue by ystolyarchuk** [ngneat/until-destroy#55]
Unsubscribe doesn't work on Angular 9 but works on correct Angular 8

**Comment by NetanelBasal** [comment]
Duplicate of #52

**Comment by ystolyarchuk** [comment]
@NetanelBasal I am using ngx-take-until-destroy, and it doesn't work yet

**Comment by arturovt** [comment]
Are you able to create a _minimal reproducible example_ for us?

**Comment by NetanelBasal** [comment]
@ystolyarchuk read the README before you open an issue. Thanks.
