### ISSUE TITLE
decorator causes Angular attributes not to be recognized in rare cases

### ISSUE THREAD

**Issue by rulamon** [ngneat/until-destroy#56]
I have two components in lazy loaded modules where adding the decorator causes Angular-specific attributes, like *ngIf and mat-raised-button, not to be recognized on compilation.

**Comment by NetanelBasal** [comment]
Create a minimal reproducible example, please.

**Comment by arturovt** [comment]
@rulamon any progress on this?

**Comment by rulamon** [comment]
@arturovt It's on my todo list, but will probably at the earliest have time for it somewhere in the course of next week.

**Comment by vcanuel** [comment]
Hi, I have noticed the same issue.
Also, I have noticed that [ngxTranslate]( https://github.com/ngx-translate/core) is unusable in components when using until-destroy in Angular 9 with Ivy. It raises  error : `The pipe 'translate' could not be found`

**Comment by arturovt** [comment]
@vcanuel we are not able to help you without seeing any reproducible example. This is like “shooting a stone” :D

**Comment by vcanuel** [comment]
@arturovt I understand. I will try to reproduce the error in a simple project.
For now, I have a suspicion that this appears only with lazy loaded routes. Indeed, If I load an other page and go to the previous route (the one that throws an error) it works.

**Comment by rulamon** [comment]
@NetanelBasal 
I tried to reproduce this in stackblitz (https://stackblitz.com/edit/until-destroy), but I can't get to actually testing it because I get this error: 
 Uncaught (in promise): Error: Cannot read property 'onDestroy' of undefined

**Comment by arturovt** [comment]
@rulamon 

Because Ivy is not enabled:

<img width="1302" alt="Снимок экрана 2020-03-18 в 16 06 47" src="https://user-images.githubusercontent.com/7337691/76981451-86426180-6932-11ea-9d27-5fee78f27f78.png">

**Comment by ipakhomov** [comment]
@rulamon please check if `aot` is set to `true` in your `angular.json` (path `projects["your-project-name"].architect.build.options`).

**Comment by arturovt** [comment]
@ipakhomov AOT and Ivy are different things and unrelated.

**Comment by ipakhomov** [comment]
@arturovt that's true. 

I faced the described above issue on Angular 9 app, which has Ivy running by default, and enabling AOT has resolved the issue.

**Comment by rulamon** [comment]
@arturovt 
I got it working but I can't reproduce the problem in Stackblitz, even though the issue still occurs in the real app.

**Comment by arturovt** [comment]
Can this be closed? Seems like it's been open since February but no one hasn't provided _minimal reproducible example_ :slightly_smiling_face:
