### ISSUE TITLE
Calling ngOnDestroy on test does not complete subscription

### ISSUE THREAD

**Issue by masimplo** [ngneat/until-destroy#60]
"@angular/core": "9.0.2",
    "rxjs": "6.5.4",
    "@ngneat/until-destroy": "7.1.1",
    "jasmine-core": "3.5.0",

On a component defined as 

```typescript
@UntilDestroy()
@Component({
  templateUrl: 'none-improvement.html',
  selector: 'cv-none-improvement-page',
  styleUrls: ['none-improvement.scss']
})
export class NoneImprovementPageComponent implements OnInit, OnDestroy {
  public firstName: string;

  constructor(
    private _user: UserProfileStore,
  ) {
  }

  public ngOnInit() {
    this._user.profile$
      .pipe(
        untilDestroyed(this)
      )
      .subscribe(u => this.firstName = u.get('firstName'));
  }

  public ngOnDestroy() {
    //
  }
}
```

I write this test:

```typescript
  it('stops getting first name from user profile after destroy', () => {
    expect(sut.firstName).toBeUndefined();
    sut.ngOnInit();
    mockUserProfileStore.profileSubject$.next(new UserProfile(<any>{ firstName: 'testName' }).toImmutable());
    expect(sut.firstName).toEqual('testName');
    sut.ngOnDestroy();
    mockUserProfileStore.profileSubject$.next(new UserProfile(<any>{ firstName: 'newName' }).toImmutable());
    expect(sut.firstName).toEqual('testName');
  });
```
which fails. But if I use `untilDestroyed(this, 'ngOnDestroy')` passes. Is `ngOnDestroy` not the default method that triggers the unsubscription?

**Comment by jherman** [comment]
Also have this issue since upgrading to Angular 9. It seems they have broken this functionality.

**Comment by arturovt** [comment]
What would be the reason to invoke life cycle hooks manually? 🕵 

1) you've got a `ComponentFixture` with `detectChanges` and `destroy` methods that manages this stuff
2) we don't patch `ngOnDestroy` method on the prototype. You have to create a `ComponentFixture` and manage it via its methods

**Comment by arturovt** [comment]
What would be the reason to invoke life cycle hooks manually? 🕵

1) you've got a `ComponentFixture` with `detectChanges` and `destroy` methods that manages this stuff
2) we don't patch `ngOnDestroy` method on prototypes. You have to create a `ComponentFixture` and manage it via its methods. The view information is stored in the component definition static property on the component class (with on destroy listener).

**Comment by masimplo** [comment]
Well, as many other teams, we are testing many components (those that have no need to test UI) in unit tests without using Testbed. The component is instantiated manually using new and triggering the lifecycles hooks on demand.

**Comment by arturovt** [comment]
The current behavior is expected. As I said calling `ngOnDestroy` manually should NOT unsubscribe from streams.

**Comment by jherman** [comment]
@arturovt As an FYI, I'm not invoking ngOnDestroy manually. When the component is destroyed when moving between routes, it not triggering properly (like it did in Angular 8). Test it out in Angular 9 - you'll see.

**Comment by arturovt** [comment]
I tested, it works for me... If you don't provide any reproduction then I see no reason to continue the dialogue, because it's like "shooting a stone". 😉

**Comment by jherman** [comment]
Got it. Apparently I was using the other package (ngx-take-until-destroy), which was my issue. Don't know if this resolves the other folks issue.

**Comment by matodrobec** [comment]
Hello,
I have same problem. It is not unsubscribe. I am find it now.

"@angular/core": "~9.0.2",
"ngx-take-until-destroy": "^5.4.0",

**Comment by jherman** [comment]
@matodrobec That's the problem I stated. Don't use ngx-take-until-destroy. Use ngneat/until-destroy.

**Comment by arturovt** [comment]
Gentlemen, basically everything is described in the readme. I was wondering if there is something unclear.

Maybe you could poke your finger in the place where we need to strengthen the readme?

**Comment by NetanelBasal** [comment]
@arturovt same here. Maybe we need to bump the font to 100px? I think the README is super clear.

**Comment by NetanelBasal** [comment]
![image](https://user-images.githubusercontent.com/6745730/77000734-87d74e00-6961-11ea-930f-462004fffe71.png)
![image](https://user-images.githubusercontent.com/6745730/77000762-8dcd2f00-6961-11ea-9482-45167186152f.png)

**Comment by jherman** [comment]
@arturovt, @NetanelBasal 

Here's the problem as I see it. For people upgrading from < 9.0, they have the ngx-take-until-destroy library in place, and when they upgrade to 9.0, they didn't expect to change the library, as most other libraries don't have you go through that process.  So when a user upgrades to 9.0, all of a sudden your subscriptions aren't unsubscribing like they were and you go directly to the "Issues" portion of github to see if others had the issue.

**Comment by NetanelBasal** [comment]
I will add a check to the prev library. If it runs in Ivy, I'll throw.

**Comment by matodrobec** [comment]
@jherman yes, you have true

**Comment by intellix** [comment]
Regarding the documentation. I've seen that there's a new import for ivy but ignored it because I figured it was just a "fancier" way/excuse to use a decorator instead of an empty `ngOnDestroy(){ }`

Didn't realise that my app is now leaking subscriptions everywhere as they're no longer destroyed. Maybe a note to add that the old way won't work whatsoever in ivy would have cleared it for me
