### ISSUE TITLE
Doesn't work when component is inherited from parent class

### ISSUE THREAD

**Issue by leonchanuk** [ngneat/until-destroy#61]
If component A is inherited from Class B, subscriptions from component A are not unsubscribed when component is destroyed.

I could solve this by changing from 
return (type as ComponentType<T>).edir || (type as DirectiveType<T>).ecmp;
to
return (type as ComponentType<T>).ɵcmp || (type as DirectiveType<T>).ɵdir;

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR. Thanks.

**Comment by RyannGalea** [comment]
When will this be merged?

**Comment by duxor** [comment]
> When will this be merged?

Fix works, but there is no PR. I will create a new one right now, I need that in my project.

**Comment by duxor** [comment]
PR is here https://github.com/ngneat/until-destroy/pull/64

**Comment by arturovt** [comment]
@leonchanuk @duxor @RyannGalea `@7.1.4` has been published, could you give it a try?

**Comment by RyannGalea** [comment]
@arturovt  I just tested @7.1.5 on a known issue in my project and it is working as it should.
