### ISSUE TITLE
Is @UntilDestroy() always required for Angular 9/Ivy?

### ISSUE THREAD

**Issue by joshuaaa** [ngneat/until-destroy#62]
I used the migration script (https://raw.githubusercontent.com/ngneat/until-destroy/master/migration/run.js) on my project.

Universally, UntilDestroy was added to the import statements.

However, only about 80% of the files had `@UntilDestroy()` added to the class/component declaration.  I'm trying to figure out of the migration script missed these, or if they are not required.

My specific questions:

Is `@UntilDestroy()` required for EVERY `@Component` class that uses `untilDestroyed(this)` in the class?  I have 4 `@Components` that the migration didn't decorate with `@UntilDestroy()`

Is `@UntilDestroy()` required for EVERY `@Injectable` class that uses `untilDestroyed(this)` in the class?  I have 1 `@Injectable` that the migration didn't decorate with `@UntilDestroy()`

What about standard logic classes?  I have 3 business logic classes that use untilDestroyed, but didn't get decorated with `@UntilDestroy()`.

Is this the correct way:

```
@UntilDestroy()
class MyClass {
	constructor(obs: Observable<any>) {
		obs.pipe(untilDestroyed(this, 'destroy').subscribe(...);
	}

	destroy() { /* NO IMPLEMENTATION */ }
}

@Component...
class MyComponent implements OnDestroy {
	private myClass: MyClass;

	constructor() {
		this.myClass = new MyClass(obs);  // Source of obs not important.
	}

	ngOnDestroy() {
		if (this.myClass) {
			this.myClass.destroy();
			this.myClass = null;
		}
	}
}
```

Also, if possible, the original npm module should be marked as deprecated and have the readme updated with instructions to the new npm module. 

Thanks in advance.

Edit:
What about `@Directives`?  I found several `@Directive`s that were not decorated.  Do these also require `@UntilDestroy()`?

**Comment by NetanelBasal** [comment]
It seems like a bug in the migration script. Please share one example code so we can investigate. And yes, you must add the decorator anywhere you use `untilDestroyed`.

**Comment by joshuaaa** [comment]
I can't seem to get it to work with Angular 9.

Example:

```
class Tab implements OnInit, OnDestroy {
	constructor() {	
	}

	ngOnInit() {
		interval(5000)
			.pipe(untilDestroyed(this))
			.subscribe(() => { console.log('ping from Tab...'); });
	}
	
	ngOnDestroy() {	
		console.log(`Tab.ngOnDestroy`);	
	}
}

@UntilDestroy()
@Component({ ... })
export class FirstTab extends Tab implements OnInit, OnDestroy {
	constructor() {	
	}

	ngOnInit() {
		super.ngOnInit();
		interval(5000)
			.pipe(untilDestroyed(this))
			.subscribe(() => { console.log('ping from FirstTab...'); });
	}
	
	ngOnDestroy() {	
		super.ngOnDestroy();
		console.log(`FirstTab.ngOnDestroy`);	
	}
}

@UntilDestroy()
@Component({ ... })
export class SecondTab extends Tab implements OnInit, OnDestroy {
	constructor() {	
	}

	ngOnInit() {
		super.ngOnInit();
		interval(5000)
			.pipe(untilDestroyed(this))
			.subscribe(() => { console.log('ping from SecondTab...'); });
	}
	
	ngOnDestroy() {	
		super.ngOnDestroy();	
		console.log(`SecondTab.ngOnDestroy`);
	}
}

 // Included in FirstTab
@UntilDestroy()
@Component({ ... })
export class Widget implements OnInit, OnDestroy {
	constructor() {	
	}

	ngOnInit() {
		super.ngOnInit();
		interval(5000)
			.pipe(untilDestroyed(this))
			.subscribe(() => { console.log('ping from Widget...'); });
	}
	
	ngOnDestroy() {	
		super.ngOnDestroy();	
		console.log(`Widget.ngOnDestroy`);
	}
}
```

When I bounce back and forth between tabs, I see the '{name}.ngOnDestroy' statements for all classes.  However, only the interval for the Widget is cleaned up.  The intervals for the Tabs are never cleared.  Instead, new ones are created.  If I bounce back and forth a few times times, I end up with 10+ ping statements.

I didn't have any problems before switching to Angular 9 and '@ngneat/until-destroy' (from 8 and 'ngx-take-until-destroy').

I tried adding `@UntilDestroy()` to the base Tab class, but I get this error:
Uncaught TypeError: Cannot read property 'onDestroy' of undefined
    at decorateDirective (<anonymous>:96852:45)


Any ideas what I'm doing wrong?

Is untilDestroyed no longer supported classes / components that use inheritance?

**Comment by joshuaaa** [comment]
Okay, looks like someone else already fixed this in a different branch:
https://github.com/starn2222/until-destroy/commit/b55b735158581bfcf166bf5a0ef1e2123b2d3d24

Any idea when this change will make it into the npm module?

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR

**Comment by NetanelBasal** [comment]
Regarding the migration, it works only on Component/Directives. In your case, it's a simple class.
