### ISSUE TITLE
Extend use-cases for custom destroy method

### ISSUE THREAD

**Issue by artaommahe** [ngneat/until-destroy#66]
With current custom destroy method implementation there are some issues

Playground for both cases here
https://ng-run.com/edit/LxkqzZQCoAv8i1KRl7Uj?open=app%2Fsome.service.ts

- having two destroy methods (for different streams) and calling one of them completes all other streams
  - press start
  - press start2
  - see two intervals in console
  - press either stop or stop2
  - both intervals complete (should complete only one)

- cannot use operator for start-stop case when you need to unsubscribe (after new subscriptions) multiple times during service lifetime

  (only first start/stop buttons now)
  - press start
  - press stop
  - press start again
  - press stop again
  - interval does not complete

It's real world use-cases from our apps where are a lot of such singleton services with start/stop methods for some pages business-logic.

**Comment by arturovt** [comment]
@artaommahe Hey. I've published `@7.1.3`, could you give it a try?

**Comment by artaommahe** [comment]
@arturovt second case is fixed, thx. First one is still here - calling one of the destroy methods complete every stream, even that is bound to other destroy method

**Comment by arturovt** [comment]
Thanks for clarifying, will look tomorrow.

**Comment by arturovt** [comment]
@artaommahe `@7.1.5` has been published.

**Comment by arturovt** [comment]
@artaommahe If you find a time to check it and it works then close the issue, or ping me here if you find another one. Cheers.

**Comment by artaommahe** [comment]
@arturovt it works, thank you. Finally we can replace our local operator with `until-destroy` lib )
