### ISSUE TITLE
Component stops working if component class is references in itself

### ISSUE THREAD

**Issue by pedrolsamaral** [ngneat/until-destroy#72]
Components that reference their classes in themselves stop working. For instance - the use case of providing a custom Angular Material MatFormFieldControl which references the component class in the Component decorator:

`@Component({
  ...
  providers: [{provide: MatFormFieldControl, useExisting: MyTelInput}],
})
@UntilDestroy()
class MyTelInput implements MatFormFieldControl<MyTel> {
  ...
}`

(from: https://material.angular.io/guide/creating-a-custom-form-field-control)

It will throw an exception like the following:

> my-tel-input.component.ts:XX Uncaught ReferenceError: MyTelInput_1 is not defined

Removing UntilDestroy and untilDestroyed makes it work again.

**Comment by arturovt** [comment]
Hey, could you provide a _minimal reproducible example_? Thanks.

**Comment by pedrolsamaral** [comment]
I'm struggling to create an online example with it but I found out that the problem is coming due to having the compilation target set to `"es5"`. 

In my particular case I can simply move to `"es2015"` since I don't really need to support older browser versions, but if you still want to replicate the issue it should be easy to do it with the code generated from a regular 'ng new'.

After the 'ng new' generates the code, change the following:

- app.component.ts
Add `@UntilDestroy `
Add `  @ViewChild(AppComponent)
  self: AppComponent;`

- tsconfig.json
change target to "`es5"`

**Comment by arturovt** [comment]
You can avoid creating an online example. Just create a git repo, push your app and give the link.

**Comment by pedrolsamaral** [comment]
Here you go:

https://github.com/pedrolsamaral/until-destroy-self-ref

**Comment by arturovt** [comment]
In your example with `MatFormFieldControl` first of all, you have to wrap classes in the `forwardRef` function (if you use `useExisting`): `useExisting: forwardRef(() => MyTelInput)`. This is a normal behavior.

Regarding your example I just tested it out:
```ts
@Directive()
class JustSomeCoolDirective {}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  providers: [{ provide: JustSomeCoolDirective, useExisting: forwardRef(() => AppComponent) }],
})
@UntilDestroy()
export class AppComponent {
  constructor(private injector: Injector) {}

  ngOnInit() {
    console.log(this.injector.get(JustSomeCoolDirective));
  }
}
```

And it works.

**Comment by pedrolsamaral** [comment]
Even though there's that work-around (when compared to the documentation example that a lot of people might be using directly) I think there might be other use cases where it won't be as easy to fix (i.e. recursive components that inject their parent)

**Comment by arturovt** [comment]
I'm not able to test it out and see what's wrong w/o the reproduction :(

**Comment by arturovt** [comment]
I just copied that example from stackblitz locally and it works for me, seems like you're doing something wrong:

![image](https://user-images.githubusercontent.com/7337691/78421660-ff93c100-7661-11ea-9d5c-cfd95c22172b.png)

![image](https://user-images.githubusercontent.com/7337691/78421673-2520ca80-7662-11ea-80d8-99d4c7d8fece.png)

Consider providing reproductions, please.
