### ISSUE TITLE
@UntilDestroy() Decorator, stops Translation pluggin from working

### ISSUE THREAD

**Issue by sithwarrior** [ngneat/until-destroy#74]
I honestly dont know if im doing something wrong, but updating to the ivy version of this plugin, I find that when I add the `@UntilDestroy()` Decorator to my component, and reload that specific page, I get the following error in my console

`ERROR Error: Uncaught (in promise): Error: The pipe 'translate' could not be found!
Error: The pipe 'translate' could not be found!`

Im using the latest version of [ngx-translate ](https://github.com/ngx-translate/core) .

The super wierd thing is, if i start my spa in a page with translations, but no observables/Until destroy, and the navigate to the page/component that uses `@UntilDestroy()` then there is no problem.  But starting the spa on the page/component with both translation and `@UntilDestroy()`, creates the error, and breaks the component.

**Comment by arturovt** [comment]
Please, provide a _minimal reproducible example_.

**Comment by NetanelBasal** [comment]
I think it's time to migrate to [Transloco](https://github.com/ngneat/transloco/) :)

Please, provide a minimal reproducible example.

**Comment by sithwarrior** [comment]
Just tried poking around it some more, and migrated to **Transloco**, to try it out, however Im faced with the same issue.

For some reason, when handling the template, the `pipeRegistry` is null, when i set the `@UntilDestroy()` decorator.

So now i get the following error:

`ERROR Error: Uncaught (in promise): Error: The pipe 'transloco' could not be found!

Error: The pipe 'transloco' could not be found!
    at getPipeDef$1 (core.js:25172)
    at ɵɵpipe (core.js:25139)
    at ChecklistsPage_Template (template.html:6)
    at executeTemplate (core.js:7632)
    at renderView (core.js:7457)
    at renderComponent (core.js:8649)
    at renderChildComponents (core.js:7316)
    at renderView (core.js:7482)
    at ComponentFactory.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.ComponentFactory.create (core.js:23068)
    at ViewContainerRef.createComponent (core.js:10400)
    at resolvePromise (zone.js:832)
    at resolvePromise (zone.js:784)
    at zone.js:894
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:27950)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:601)`


I'll try and make a reproducible example later today.

**Comment by arturovt** [comment]
Something went wrong.... :smile: 

That would be great. I'll be able to test it out and help you.

**Comment by NetanelBasal** [comment]
@sithwarrior seems to work as expected. https://stackblitz.com/edit/ngneat-transloco-ivy

**Comment by sithwarrior** [comment]
> @sithwarrior seems to work as expected. https://stackblitz.com/edit/ngneat-transloco-ivy

Yes.. It also work, when I create a completely empty project from scratch, so Im having a hard time tracking this down.

In my current project, Whenever i use the `@UntilDestroy()` Decorator, the TViewConstructor inside core.js (Angular Core Ivy), for my page has an empty pipeRegistry, and errors out. I'll try and align all my dependecies, but they are Angular 9.1.1 etc. as your example.. 

So just ignorre me for now, I'll be back with a fix, or something you can reproduce :-)

**Comment by LucasKubicki** [comment]
I have the same kind of weird bug, im using angular 9 in ng serve mode with aot false, only happens when i load directly a route in a lazy load module if the component use @UntilDestroy() i have some bug like async pipe not found, *ngIf not declared ect.. like the commonmodule cant load if im coming from another route no problem, if i delete @UntilDestroy no problem too, i will try to reproduce on a minimal project.  With aot true, when i build ect.. no problem too

**Comment by LucasKubicki** [comment]
https://github.com/LucasKubicki/bug-ngdestroy ng serve try to access 
Error: The pipe 'async' could not be found!
Error: The pipe 'async' could not be found!

If i delete UntilDestroy() its work fine.

Ty for your time.

@NetanelBasal

**Comment by sithwarrior** [comment]
I have had no luck in creating a minimial reproducible version, bit through debugging, I can see that the order the anguler compiler works changes when `@UntilDestroy` is used to decorate. 

When used the eepipe method is called before the template contaning the pipe, has been compiled in the create tview method.

**Comment by arturovt** [comment]
`@7.1.6` has been published. Could you try it out?

**Comment by sithwarrior** [comment]
Thx @arturovt and @NetanelBasal  it works now, when updating to 7.1.6
