### ISSUE TITLE
UntilHook/UntilCall

### ISSUE THREAD

**Issue by ZeevKatz** [ngneat/until-destroy#76]
First of all, I’d like to say thanks to you guys for maintaining such an incredible library! 

And here is my **BREAKING-CHANGE** suggestion that could be useful in some cases when dealing with subscriptions in other life-cycle hooks such as `OnChanges`.

I faced issues when integrating with the client API of Tableau. For those who are not familiar with this tool, it’s a BI solution that helps you to bring insights using visualizations over your data.
In my case, I was asked to integrate some of their client API capabilities into our application by wrapping it with a component.
 
The object that I used from their API was Viz, which is a common name they use for views and dashboards.
For simplicity, I’ll not get into details about the whole API but focus on the events registration they provide for listening to any event that occurred in the Viz.

Here is a code snippet from `OnChanges` implementation of the `TableauVizComponent` that I’ve created.

```ts
...

async ngOnChanges({ identifier, options, filters, registerEvents }: SimpleChanges) {
    if (identifier || options || filters) {
      this.disposeCurrentVizIfExists();
      const viz = await this.createViz(this.identifier, { ...this.options, ...this.filters }).toPromise();
      this.currentVizSubject$.next(viz);
    }

    if (this.currentViz && registerEvents) {
      this.registeredEventsSubscription && this.registeredEventsSubscription.unsubscribe();
      this.registeredEventsSubscription = this.registerEventListeners(this.registerEvents)
        .pipe(untilDestroyed(this))
        .subscribe(event => this.event.emit(event));
    }
  }

...

/**
   * Adds event listeners to the given list of Tableau events on the current {@link Viz}.
   *
   * @param {T[]} eventNames - A list of Tableau event names to register.
   * @returns {Observable<DiscriminateTableauEvent<T>>} An `Observable` that emits the events provided in the list of event names.
   */
registerEventListeners<T extends TableauEventName>(eventNames: T[]): Observable<DiscriminateTableauEvent<T>> {
    return this.currentViz$.pipe(
      switchMap(viz => {
        const events = eventNames.map(eventName => {
          return fromEventPattern<DiscriminateTableauEvent<T>>(
            handler => viz.addEventListener(eventName, handler),
            handler => viz.removeEventListener(eventName, handler)
          );
        });
        return merge(...events);
      }),
      map(event => ({ type: event.getEventName(), ...event }))
    );
  }

...
```

As you can see, after creating a new Viz with its ID, options, and filters that I got as inputs, in case that the `registerEvents` input was changed, I start listening to the events in the list and stop listening when the event name omitted from the list.

So let's get into the point, I have to unsubscribe from the prev events on any change of `registerEvents` input, and to do this, I have to keep a reference to the subscription on the class and unsubscribe when it exists before re-subscribing to the new list of events.

It could be simpler if the `untilDestroy` would be changed to something more generic that handle additional types of life-cycle hooks such as `OnChanges`, or even better, supporting to unsubscribe on any method call of the class.

So what are you think about it? Is it worth the effort?

**Comment by arturovt** [comment]
I read your issue 2 times. I didn't understand your purpose. What will you want to achieve?

**Comment by ZeevKatz** [comment]
@arturovt Supporting to unsubscribe observables in different life-cycle hooks other than `OnDestroy`.

**Comment by arturovt** [comment]
Imho this is out of scope and can be kept out of the library. @NetanelBasal thoughts?

**Comment by NetanelBasal** [comment]
Same here
