### ISSUE TITLE
TypeError: Cannot read property 'onDestroy' of undefined

### ISSUE THREAD

**Issue by YaroslavPetryk** [ngneat/until-destroy#77]
Throws this error while trying to run tests using Jest

TypeError: Cannot read property 'onDestroy' of undefined
 at decorateDirective (node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:69:52)
      at node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:78:7

**Comment by arturovt** [comment]
Provide a _minimal reproducible example_.

**Comment by YaroslavPetryk** [comment]
Fixed by adding "postinstall": "ngcc" to package.json
