### ISSUE TITLE
Error: The pipe 'async' could not be found!

### ISSUE THREAD

**Issue by LucasKubicki** [ngneat/until-destroy#78]
Hello,

I have some error with lazy load + aot false on ng serve.
Like the commonModule don't load in this case. If i delete untilDestroy from the component its work fine.

https://github.com/LucasKubicki/bug-ngdestroy ng serve try to access http://localhost:4200/customers

Ty for your time ;)

**Comment by arturovt** [comment]
@NetanelBasal 

That is tricky. After my debugging, I've noticed that this exception:
![image](https://user-images.githubusercontent.com/7337691/79196330-90c02000-7e38-11ea-8d4b-ef6fa318d821.png)

Is thrown when we call `getDef(type)`, where `ɵcmp` is a getter. Still not got to the very roots of why it happens in JIT mode.

But actually... just thinking aloud...

Could we simply determine if it's a JIT mode:
```js
type.hasOwnProperty('__annotations__')
```
And wrap `decorateDirective(target, options)` into:
```js
Promise.resolve().then(() => decorateDirective(target, options))
```

That promise will be resolved before APP_INITIALIZER runs.

**Comment by NetanelBasal** [comment]
@arturovt what about this solution:

```ts

function decorateDirective(type, options) {
  const isJIT = type.hasOwnProperty('__annotations__');
  if (isJIT) {
    const compGetter = Object.getOwnPropertyDescriptor(type, 'ɵcmp').get;

    Object.defineProperty(type, 'ɵcmp', {
      get: function() {
        const def = compGetter();

        // TODO: Check if we should run it only on the first time
        def.onDestroy = decorateNgOnDestroy(def.onDestroy, options);
        markAsDecorated(def);
        return def;
      }
    });
  } else {
    const def = getDef(type);
    def.onDestroy = decorateNgOnDestroy(def.onDestroy, options);
    markAsDecorated(def);
  }


}
```

**Comment by NetanelBasal** [comment]
Your solution works too, and it's more readable, of course, but it's `async`. As almost no one uses `JIT` mode these days, I'll leave the decision to you.

**Comment by arturovt** [comment]
@NetanelBasal I like this solution too.

Two heads are better than one :joy:

**Comment by arturovt** [comment]
`@7.1.6` has been published. Could you try it out?

**Comment by arturovt** [comment]
I upgraded package to `7.1.6` in your github repo and it works.

**Comment by LucasKubicki** [comment]
Yes its work, ty for your time ;)
