### ISSUE TITLE
Doesn't work with storybook

### ISSUE THREAD

**Issue by paradoxm** [ngneat/until-destroy#82]
I am using storybook https://github.com/storybookjs/storybook. When it builds when i catch error, because there is no private ɵcmp object in the component.

![image](https://user-images.githubusercontent.com/12410438/79485898-5e2c4800-802f-11ea-9d73-88553a005463.png)

I caught the error in this line
![image](https://user-images.githubusercontent.com/12410438/79486317-f32f4100-802f-11ea-99fa-203d05e38096.png)

Will be your library support the storybook?

**Comment by arturovt** [comment]
I answered in your previous issue: Provide a minimal reproducible example.

**Comment by arturovt** [comment]
Your storybook app is running using _view engine_ compiler.

**Comment by paradoxm** [comment]
I use one component for the project and the storybook. I need to wrap component with the decorator UntilDestroy for the project, but it cause that the storybook will be broken. I don’t understand what should I do in this situation? (((

**Comment by paradoxm** [comment]
I foun temporary solution. I have added

```ts

export function isIvyComponent(componentType: Type<any>): boolean {
  return (componentType as any)[ɵNG_COMP_DEF] !== undefined;
}

export function isIvyDirective(directiveType: Type<any>): boolean {
  return (directiveType as any)[ɵNG_DIR_DEF] !== undefined;
}

export function isIvyModule(moduleType: Type<any>): boolean {
  return (moduleType as any)[ɵNG_MOD_DEF] !== undefined;
}

export function isIvyPipe(pipeType: Type<any>): boolean {
  return (pipeType as any)[ɵNG_PIPE_DEF] !== undefined;
}
```
and ad condition 

```ts
function decorateDirective(
  type: DirectiveType<unknown> | ComponentType<unknown>,
  options: UntilDestroyOptions
) {
  if (isIvyComponent(type) || isIvyDirective(type) || isIvyPipe(type)) {
    const isJIT = type.hasOwnProperty('__annotations__');

    if (isJIT) {
      decorateDirectiveJIT(type, options);
    } else {
      const def = getDef(type);
      (def as { onDestroy: () => void }).onDestroy = decorateNgOnDestroy(def.onDestroy, options);
      markAsDecorated(def);
    }
  }
}
```

now story book works correct

**Comment by arturovt** [comment]
Your storybook doesn't work because it's running using VE-compatible compiler. That code that you've pasted and added to your application is just _to silent that error_.
