### ISSUE TITLE
ParentService - Cannot read property 'onDestroy' of undefined

### ISSUE THREAD

**Issue by tft7000** [ngneat/until-destroy#84]
Hello. thanks for this great extension!

There might be a problem with parent services that have subscriptions and their child services that are actually in use by a component: I get the "_Cannot read property 'onDestroy' of undefined_" error under Angular 9.

I tried to reproduce the problem on StackBlitz: https://stackblitz.com/edit/angular-fk8a1t

I have a base service that uses a subscription and implements `untilDestroyed`:
```
@UntilDestroy()
export class BaseService {
  constructor() {
    interval(1000)
      .pipe(untilDestroyed(this))
      .subscribe(() => console.log('BaseService tick '));
  }
}
```

and a child service that extends the base service:
```
@Injectable({
  providedIn: 'root'
})
export class ChildService extends BaseService {
  constructor() {
    super();
  }
}
```

if the child service is used, the "_Cannot read property 'onDestroy' of undefined_" error appear in the console.

Note: locally I tried adding `ngcc` to the postinstall section, with no success. I did the same in StackBlitz, however, I don't know, if this has an effect in that environment.

My current workaround is using a regular `stop$` subject without using untilDestroyed.

**Comment by NetanelBasal** [comment]
First, `ChildService` is a wide-app singleton. Second, you need to add `Injectable` to the parent.

**Comment by tft7000** [comment]
@NetanelBasal : thanks for your answer.

I cannot make the parentService injectable, as it is an abstract service that needs information from the child service thru the constructor.
In my case I get the following error: "_No suitable injection token for parameter 'entityName' of class 'BaseEntityService'._"

does this mean, without the `Injectable` decorator `untilDestroyed` does not work? 
or does it mean, that I might doing some nasty things I shouldn't do?

**Comment by NetanelBasal** [comment]
> without the Injectable decorator untilDestroyed does not work

Correct. This is the new behavior with Ivy

**Comment by tft7000** [comment]
@NetanelBasal : thanks for the fast and helpful answers
