### ISSUE TITLE
Possible to put a peerDependency in the old module?

### ISSUE THREAD

**Issue by freon27** [ngneat/until-destroy#85]
Hi :)

We updated to Angular 9 a while ago without realising there was a problem with the previous module. Obviously our own fault for not checking but we imagined that this module was only really tied to RXJS version.

I just wondered as a suggestion... is there a reason not to put a peerDependency of Angular < 9 on the old module so that people get a warning when they upgrade?  I can see that the new module is more generic and not specific to Angular but the old one is an `ngx-` module so presumably it was designed to be used with Angular.

**Comment by freon27** [comment]
Or maybe putting a deprecate warning on?

**Comment by NetanelBasal** [comment]
I've deprecated the module using `npm deprecate` and wrote to use this library instead. Thanks for the suggestion.
