### ISSUE TITLE
Error: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by davidecampello** [ngneat/until-destroy#86]
Hi, I'm having this error:
![image](https://user-images.githubusercontent.com/21193922/80291272-88c38280-874c-11ea-849b-64875429cbcd.png)

I've only added @UntilDestroy() and .pipe(untilDestroyed(this)) into a component inside an Angular 9.1.0 app.

Thanks

**Comment by arturovt** [comment]
Could you provide a reproduction?

**Comment by arturovt** [comment]
You're getting this error because Ivy is disabled. Same I do if I disable it:
![image](https://user-images.githubusercontent.com/7337691/80291974-fd052280-875a-11ea-9264-2fadd3931da5.png)

Refer to Angular Ivy docs please.

**Comment by intellix** [comment]
Ivy is disabled on Stackblitz? https://stackblitz.com/edit/angular-vcrucd?file=src%2Fapp%2Fhello.component.ts

**Comment by NetanelBasal** [comment]
![image](https://user-images.githubusercontent.com/6745730/81057947-1c781a00-8ed6-11ea-8d5c-d04aae7ee2c7.png)

**Comment by intellix** [comment]
Getting the above error when using it on Directives in Jest unit tests :/
