### ISSUE TITLE
The ɵcmp and ɵdir properties are not configurable in production builds (TypeError: Cannot redefine property)

### ISSUE THREAD

**Issue by idpaterson** [ngneat/until-destroy#88]
Angular [allows configuration of the `ɵcmp` and `ɵdir` properties only in dev mode](https://github.com/angular/angular/blob/698b0288bee60b8c5926148b79b5b93f454098db/packages/core/src/render3/jit/directive.ts#L150-L170). While the fix for #78 works in development mode, in a production build I see `Uncaught TypeError: Cannot redefine property: ɵdir`. I have temporarily reverted from 7.1.6 to an earlier version.

JIT build, Ivy enabled, but no lazy loaded components so I am unable to test the original issue in #78. Perhaps the alternative solution there is worth exploring?

**Comment by NetanelBasal** [comment]
The wonders of Angular. I don't know why they did this. We can use @arturovt  solution or drop support for JIT mode. I leave the decision to you @arturovt.

**Comment by arturovt** [comment]
I'm just wondering why they keep and keep changing behaviour related to component/directive definition properties....

**Comment by NetanelBasal** [comment]
Agree.

**Comment by arturovt** [comment]
@idpaterson how can I reproduce this issue?

**Comment by idpaterson** [comment]
Here's an example with just a few lines changed from the `ng new` cli quickstart. Clone [the example](https://github.com/idpaterson/until-destroy/tree/examples/jit-decorator-bug) then

```
npm ci
ng build --prod
superstatic dist/until-destroy-jit -c superstatic.json
```

Open the link shown and you will see the blank screen issue. Rebuild with `--aot` works fine as expected.

P.S. this was the little kick I needed to fix everything up for AOT, so thanks for that :)

**Comment by arturovt** [comment]
So it works with AOT but doesn't work with JIT? Or....? Because you said that you see the error in the production build. Am I missing anything? Just want to make all details clear.

**Comment by idpaterson** [comment]
Yes it only affects JIT builds. The example is configured for JIT so the commands shown will exhibit the blank white screen and accompanying error in the browser console. If you build with `--aot` instead the sample app will work fine. It also does not affect JIT in dev mode (e.g. `ng serve` in this sample project).

I have converted the project where I originally
discovered this problem to AOT and now have no trouble using the latest until-destroy, sorry for the confusion.

**Comment by arturovt** [comment]
I cloned your issue and saw the error. I don't know if it's an issue or not, honestly... :grin: Personally, I would never run `ng build --prod` w/o `aot`, just add `aot` here:

![image](https://user-images.githubusercontent.com/7337691/81501540-9ac32a80-92e1-11ea-94ed-6f79b7f65b4c.png)

@NetanelBasal what do you think?

**Comment by idpaterson** [comment]
Personally I think it is fine to drop support for JIT, the main issue is that this ended up being a breaking change in a patch release and the kind of breaking change that may not prevent CI deployments (runtime error rather than build error). In my case it was just a staging app that went down, but it was a surprising and obscure error message. Since AOT was not always enabled by default there may be older projects like mine still using JIT despite best practices.

**Comment by arturovt** [comment]
Not sure about dropping support for JIT... For instance, I've got a huge project at a job that uses JIT compiler in dev mode because AOT is super slow...

**Comment by NetanelBasal** [comment]
Summary - We only support JIT in dev mode.
