### ISSUE TITLE
Ivy and directives - "get" of undefined

### ISSUE THREAD

**Issue by intellix** [ngneat/until-destroy#90]
After updating to `@ngneat/until-destroy` I've noticed that our tests no longer work when `@UntilDestroy` is used on a directive.

Error:
```
 FAIL  apps/play/src/app/one.directive.spec.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'get' of undefined

       7 |   selector: '[playOne]'
       8 | })
    >  9 | export class OneDirective {
         |                          ^
      10 |   constructor() {
      11 |     interval(1000).pipe(untilDestroyed(this)).subscribe(console.log);
      12 |   }

      at decorateDirectiveJIT (../../node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:77:65)
      at decorateDirective (../../node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:103:5)
      at ../../node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:116:7
      at Object.__decorate (../../node_modules/tslib/tslib.js:95:99)
      at Object.<anonymous> (src/app/one.directive.ts:9:26)
      at Object.<anonymous> (src/app/one.directive.spec.ts:1:1)
```

Basic code:
```ts
import { Directive } from '@angular/core';
import { UntilDestroy, untilDestroyed } from '@ngneat/until-destroy';
import { interval } from 'rxjs';

@UntilDestroy()
@Directive({
  selector: '[playOne]'
})
export class OneDirective {
  constructor() {
    interval(1000).pipe(untilDestroyed(this)).subscribe(console.log);
  }
}
```

Basic reproduction: https://github.com/intellix/ngneat-take-until-directive-repro/commit/64efd59bfd061fe41223aa8ed5bfd5bbc484cd3e

Probably related: https://github.com/ngneat/until-destroy/issues/86

**Comment by arturovt** [comment]
It's not working because Ivy is disabled:

![ivy-disabled](https://user-images.githubusercontent.com/7337691/81089456-12b9db00-8f05-11ea-80dc-6639446e97ea.png)

If I run `ngcc` then it works:

![ivy-enabled](https://user-images.githubusercontent.com/7337691/81089488-1c434300-8f05-11ea-8c24-3236f2b0c3b5.png)

Please, search among other issues before opening a new one... 

There already exist issues with the **same** problem.

Let's respect each other, I can't always waste my time for cloning each repo and testing it locally... :disappointed:

**Comment by intellix** [comment]
Apologies for wasting your time. It's literally a brand new project installed with Angular 9. I didn't even know there was a private ivyEnabled flag you could import to check for that.

Why would a newly installed Angular 9 project not use ivy during tests and why would I need to opt into that? It's enabled by default but not in tests?

**Comment by arturovt** [comment]
https://github.com/ngneat/until-destroy/issues/54#issuecomment-586980049
