### ISSUE TITLE
Angular 9 invalid package name error

### ISSUE THREAD

**Issue by lajuma** [ngneat/until-destroy#92]
Get this error on running `npm i @ngneat/until-destroy` in my project (Angular v 9.1)

```
code EINVALIDPACKAGENAME
Invalid package name "__ngcc_entry_points__.json": name cannot start with an underscore
```

any suggestions?

**Comment by lajuma** [comment]
looks like this is not an issue with your package

**Comment by BuzzVenter** [comment]
Hi @lajuma what was your solution to this error?

**Comment by mengyang1229** [comment]
@BuzzVenter https://stackoverflow.com/questions/62288293/ionic-invalid-package-name-ngcc-entry-points-json

**Comment by mengyang1229** [comment]
rm -rf node_modules

npm install

**Comment by avaiyakirtib** [comment]
This works for me!

**Comment by Kade-95** [comment]
It didn't work for me

**Comment by ArcosBinary** [comment]
@Kade-95 
when deleting node_module doesn't work you also need to delete the package-lock.json

**Comment by Sampath-Lokuge** [comment]
This works for me: https://stackoverflow.com/a/71985779/1077309
