### ISSUE TITLE
e2e tests fail : Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by happyBanshee** [ngneat/until-destroy#94]
When running e2e test after error happens
```
[12:38:46] I/launcher - Running 1 instances of WebDriver
[12:38:46] I/direct - Using ChromeDriver directly...
[12:38:49] E/launcher - Error: TypeError: Cannot read property 'get' of undefined
    at decorateDirectiveJIT (/**/node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:77:65)
    at decorateDirective (/**/node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:103:5)
    at /**/node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:116:7
    at Object.__decorate (/**/node_modules/tslib/tslib.js:97:99)

```

Project was recently updated to Angular 9.

**Comment by arturovt** [comment]
Provide a _minimal reproducible example_, please.

**Comment by Adrael** [comment]
Same issue here, while running unit tests with Jest in an Nx workspace:

![image](https://user-images.githubusercontent.com/866900/82072104-5e277280-96d7-11ea-8636-5b849c8069aa.png)

After a little bit of digging, it seems that the `getDefName` method ([here](https://github.com/ngneat/until-destroy/blob/master/src/lib/internals.ts#L102)) is not able to properly identify the input type.

Hacking the code with logs I get:
```typescript
console.log(type.hasOwnProperty(NG_COMPONENT_DEF)); // false
console.log(type.hasOwnProperty(NG_DIRECTIVE_DEF)); // false
``` 
Which will in turn obviously make it impossible to retrieve the getter ([here](https://github.com/ngneat/until-destroy/blob/master/src/lib/until-destroy.ts#L77)).

I have no time to post a reproducible example just yet but will do whenever I can if someone else does not first.

Maybe this will help:

```
Angular CLI: 9.1.4
Node: 12.10.0
OS: darwin x64

Angular: 9.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.4
@angular-devkit/build-angular      0.901.4
@angular-devkit/build-ng-packagr   0.901.4
@angular-devkit/build-optimizer    0.901.4
@angular-devkit/build-webpack      0.901.4
@angular-devkit/core               9.1.4
@angular-devkit/schematics         9.1.4
@ngtools/webpack                   9.1.4
@schematics/angular                9.1.4
@schematics/update                 0.901.4
ng-packagr                         9.1.2
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
```

Thanks 😃

**Comment by arturovt** [comment]
@Adrael 

> I have no time to post a reproducible example

The same for me. I've got a limited amount of time and I would rather be spending my time fixing that issue than trying to reproduce it. ;)

**Comment by Adrael** [comment]
@arturovt made it quickly, check this [sample repository](https://github.com/Adrael/ngneat-until-destroy-issue).

Run `npm i` then `nx test` and you should see the error:

```typescript
 ~/.../ngneat-until-destroy-issue:master > nx test                                                                   
 FAIL  apps/ngneat-until-destroy-issue/src/app/app.component.spec.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'get' of undefined

       8 |   styleUrls: ['./app.component.scss'],
       9 | })
    > 10 | export class AppComponent {
         |                          ^
      11 |   title = 'ngneat-until-destroy-issue';
      12 | }
      13 | 

      at decorateDirectiveJIT (../../node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:77:65)
      at decorateDirective (../../node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:103:5)
      at ../../node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:116:7
      at Object.__decorate (../../node_modules/tslib/tslib.js:97:99)
      at Object.<anonymous> (src/app/app.component.ts:10:26)
      at Object.<anonymous> (src/app/app.component.spec.ts:2:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.688s
Ran all test suites.

```

**Comment by arturovt** [comment]
@Adrael 

This doesn't work because Ivy is disabled:

![disabled](https://user-images.githubusercontent.com/7337691/82077002-540d7000-96e7-11ea-9426-c82af3376336.png)

If I run `ngcc` then it works:

![enabled](https://user-images.githubusercontent.com/7337691/82077022-5a035100-96e7-11ea-9eb8-67d4c5d5935c.png)

**Comment by arturovt** [comment]
@Adrael 

Man, I will tell you honestly there are dozen of issues with **exactly the same** problem. This seems very frustrating that people just keep opening issues w/o checking Angular Ivy docs and other issues.

**Comment by Adrael** [comment]
@arturovt thanks for the quick fix, indeed it works!

> just keep opening issues w/o checking Angular Ivy docs

FYI, I was not suspecting this to be my issue, given that I have
`"postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"`
in my package.json which ran straight after installing the lib.
Actually, this is done by Nx by default, and is also available in the package.json in the sample repository, which also ran when you installed the repository on your machine.
Though simply running `ngcc` made it work....

> This seems very frustrating

I guess this is how open source works...
But even if I didn't have the time as you can see I tried my best to help you debug the issue although I'm not the one opening it... So you should not blame me for this 😉

Anyway, thanks for your quick reply, it was very much appreciated.

Keep up the morale and the good work!

**Comment by arturovt** [comment]
@Adrael 

Hehe. I'm saying in general. We just really keep having and having the same issues. Glad to help! :wink:

**Comment by arturovt** [comment]
@Adrael 

> Actually, this is done by Nx by default

This just forces me to make a PR to their repo to fix that... :rofl:

**Comment by jedmundo** [comment]
I am having this exact issue but when running the e2e tests with protractor. Do you guys know if its related?

**Comment by akimlyubchenko** [comment]
I'm using `@ngneat/until-destroy@8.x.x` package and that he crashes all tests. After downgrading it to 7.x.x version all tests with @UntilDestroy decorator was crashed. If you use it, try to upgrade it to 8.x.x (but pay attention. @ngneat/until-destroy 8.x.x support angular 10.0.5+ only :D)
